causalens/dara

packages/dara-components/changelog.md, packages/dara-components/js/common/switch/switch.tsx
When `Switch` was used with a horizontal` Label` it did not appear centered by default.
The issue was due Switch being narrower than all our other interactive components. So that it would behave similarly I have added some margins so that its total height is the same of input and select.
This has been added on Dara instead of Dara-UI as it goes against our components structure. They do not have margins in the design. For Dara for ease of use it makes sense to have the margin, but for other libraries that depend on it, e.g. platform it may not be desirable. 
The down side of this approach is that for vertical labels the spacing might end up being too great, although still would be in line with other components. Users can always override the margin or gap between label if that is not …
=> Fix: DO-1584 label switch not centred vertically

.github/prace.yml, packages/dara-components/changelog.md, packages/dara-components/dara/components/common/select.py, packages/dara-components/js/common/select/select.tsx
It was found that when passing `items` to `Select` component as a `DerivedVariable`, if items was not a List[Item] then the component would error. 
Added a check to see if items is a list of strings and if so to convert it into an array of items for consumption by the component. 
For NonDataVariables this conversion is done in the python side.
I have also updated prace.js to only require the first two checkboxes. I think the checkboxes should be accurate with what has been covered in the PR rather than just checking everything for the sake of it. 
None
Locally by passing a DerivedVariable with a List[Item] and one with List[string]
=> Fix: DO-1576 select does not accept a derived variable with an array of strings

tooling/scripts/docs-upload.py
The zip format expected by our docs system includes a top-level `__docs` folder within the zip. The previous implementation here included just the `__docs` contents instead.
The zipping script now prefixes each file with `__docs/` which makes it include a `__docs` folder within the zip.
By running the script locally, verifying the resulting structure
See contents of the zip now including a __docs folder:
=> Fix: DO-1658 prefix zipped docs files with __docs/

packages/dara-core/changelog.md, packages/dara-core/dara/core/defaults.py, packages/dara-core/dara/core/visual/components/__init__.py, packages/dara-core/dara/core/visual/components/dynamic_component.py
Exposed `DynamicComponent` as a Python class. Normally it is used under-the-hood by `@darajs/core` to render component trees. It can now be used directly in advanced use cases to serialize components and render them dynamically.
Note that using DynamicComponent in this way under the hood ends up rendering two instance of DynamicComponent (since it is used to resolve DynamicComponent itself first).
Tested in a local app
```python
select = Select(items=DerivedVariable(...), value=...).dict()
config.add_page(name='dynamic render', content=DynamicComponent(component=select))
```
=> Feat: DO-1708 Expose DynamicComponent as a class

packages/dara-core/dara/core/js_tooling/js_utils.py
Issue discovered when attempting to bundle JS in a project with custom JS. The `copy_js` option would copy contents of a local JS folder directly into the output folder, rather than placing them in a folder with the original name. E.g.
```
- project_name/
- js/
- my_file.tsx
- output_folder/
- my_file.tsx
```
whereas correct behaviour should be
```
- project_name/
- js/
- my_file.tsx
- output_folder/
- js/
- my_file.tsx
```
Fixed by appending the original directory basename to the destination path.
Tested in a local project
=> Fix: DO-1724 `copy_js` param in `bundle_js` not working properly

packages/dara-core/dara/core/configuration.py, packages/dara-core/dara/core/definitions.py, packages/dara-core/dara/core/interactivity/actions.py, packages/dara-core/dara/core/internal/dependency_resolution.py, packages/dara-core/dara/core/internal/registries.py, packages/dara-core/dara/core/internal/registry.py, packages/dara-core/dara/core/internal/registry_lookup.py, packages/dara-core/dara/core/internal/routing.py, packages/dara-core/dara/core/main.py, packages/dara-core/dara/core/visual/dynamic_component.py, packages/dara-core/js/shared/dynamic-component/dynamic-component.tsx, packages/dara-core/js/shared/utils/use-component-registry.tsx
Currently when render actions/derived variable/pycomponent, server will look for entry in the corresponding registry. If it doesn’t exist, will raise a KeyError.
This PR is adding a new feature: when catch a KeyError, server will check if user identified their own handler, if so, the customised handler will return the entry. 
1. Implement an `add_registry_lookup()` in the ConfigurationBuilder, user can add their own handlers.
```
from dara.core import ConfigurationBuilder
config = ConfigurationBuilder()
def get_derived_variable(uid)-> DerivedVariableRegistryEntry:
def get_action(uid)-> Callable:
config.add_registry_lookup(
{
'DerivedVariable': get_derived_variable,
'Action Handler': get_action,
}
)
```
2. Implement a RegistryLookup class, its take the user defined handlers when initialise …
=> Feat: DO-1543 Support to lookup entry in external registry 

packages/dara-core/dara/core/interactivity/actions.py
1.UpdateVariable `__init__()` function executed before `utils_registry.set('RegistryLookup')`, which introduced a KeyError.
2. Edge case: utils_registry not having RegistryLookup/WebsocketManager/TaskGroup
1. Call `utils_registry.get('RegistryLookup')` in the data resolver function
2. If utils_registry has RegistryLookup, call `DataVariable.update_value()`, which will start broadcast; otherwise call `DataVariable._update()` and return the value
No
Local tested
=> Fix: DO-1543 Dataframe update action

borg.toml, lerna.json, packages/create-dara-app/pyproject.toml, packages/dara-components/package.json, packages/dara-components/pyproject.toml, packages/dara-core/changelog.md, packages/dara-core/dara/core/internal/registry_lookup.py, packages/dara-core/dara/core/internal/utils.py, packages/dara-core/package.json, packages/dara-core/pyproject.toml, pnpm-lock.yaml, poetry.lock, pyproject.toml
This PR fixes cases where now the asynchronous nature of registry lookup can cause issues when multiple requests come in at the same time, requesting the same registry key. In those cases the custom handlers can be invoked multiple times with the same value, which results in the same registry key being attempted to be registered and errors out.
The issue is fixed by implementing an `async_dedupe` decorator, which keeps track of args/kwargs that the function is being called with; invoking the method with the same set of arguments instead awaits the lock.
Including build changes for 1.1.6
Tested in a local project utilising custom registry handlers, this PR fixes the issue
=> Fix: DO-1782 parallel registry lookup errors, build 1.1.6

Makefile, packages/dara-components/changelog.md, packages/dara-components/dara/components/common/table.py, packages/dara-components/js/common/table/table.tsx, packages/dara-core/dara/core/interactivity/filtering.py, packages/dara-core/dara/core/internal/routing.py, packages/dara-core/js/shared/interactivity/data-variable.tsx, packages/dara-core/js/types/core.tsx
A bug was found where if table was sorted then the wrong chosen role was passed to the backend.
The issue turned out to be an issue with getting the value within the getItem which created a discrepancy when data was sorted from initial index to the one chosen by the user. This was also an issue for if the table selected value was changed from outside the component. The easier fix was to simply remove that part of the logic. We do need to fetch the data more often, but in this way we guarantee that regardless if selection is done in a sorted table or changed from outside that the correct index is still passed to both `onclick_row` action context and `selected_indices` Variables.
None
Locally by single and multi selecting table rows, sorted and unsorted and checking corresponding Variables …
=> Fix: DO-1452, DO-1713 fix table sort does not return the right index row

docs/best-practices/retaining-correct-variable-types.md, packages/dara-components/dara/components/smart/data_slicer/extension/filter_status_button.py, packages/dara-components/dara/components/smart/data_slicer/utils/core.py, packages/dara-core/changelog.md, packages/dara-core/dara/core/auth/definitions.py, packages/dara-core/dara/core/configuration.py, packages/dara-core/dara/core/interactivity/derived_variable.py, packages/dara-core/dara/core/internal/dependency_resolution.py, packages/dara-core/dara/core/internal/encoder_registry.py, packages/dara-core/dara/core/internal/normalization.py, packages/dara-core/dara/core/internal/routing.py, packages/dara-core/dara/core/main.py, packages/dara-core/dara/core/visual/dynamic_component.py, packages/dara-core/tests/python/utils.py
Errors occur when the backend is trying to return a component json data to the frontend, which contains datatypes in pandas/numpy. The reason behind this is fastapi doesn't know how to handle serialisation of those datatypes.
Hence, an encoder registry is introduced to handle the serialisation and deserialisation.
Defined a global encoder dict registry, in which key is a class Type, and each type have two handlers, one for serialisation and one for serialisation.
User can add their custom encoder to the global encoder dict registry by calling config.add_encoder()
None
Locally tested.
=> Feat: DO-1785 Add serialization support

packages/dara-components/changelog.md, packages/dara-components/js/common/table/table.tsx
Even with `searchable` set to True the search box did not appear over the Table component.
The issue was found due to Table's inset to be defaulted to zero. That meant that the Table was on top of the search bar. The inset is needed as a hack around some resizing issues we had in the past however it did not account for the bar being present. To fix this I have added a condition on searchable set, where if true adds some space for it.
Table unlike other components also had some padding set around it, this has been removed.
None
Locally by rendering a Table with and without searchable flag
On safari, firefox and chrome
=> Fix: DO-1862 custsup table search does not show up

borg.toml, lerna.json, packages/create-dara-app/pyproject.toml, packages/dara-components/package.json, packages/dara-components/pyproject.toml, packages/dara-core/changelog.md, packages/dara-core/dara/core/interactivity/data_variable.py, packages/dara-core/dara/core/internal/encoder_registry.py, packages/dara-core/package.json, packages/dara-core/pyproject.toml, packages/dara-core/tests/python/test_encoders.py, pnpm-lock.yaml, poetry.lock, pyproject.toml
Issue found when testing out new 1.2 changes, the default encoder for pandas.Timestamp was previously outputting a datetime object which was unserializable. Fixed by using the same isoformat method as the native datetime object uses.
Tested by modifying code directly in the project where the issue was spotted
=> Fix: DO-1902 fix default pandas.Timestamp encoder & build 1.2.2

packages/dara-components/changelog.md, packages/dara-components/js/common/table/table.tsx
After 1.2 release a horizontal scrollbar would always appear in Table component
This seems to be an issue with the AutoSizer calculating a width just slightly larger than it should.  This does not seem to happen if the component has left/right paddings above a certain threshold. While playing with it I noticed we could alternative set the width to 100% - 1px, it seems that in some cases defining a width to a parent component helps the AutoSizer. This seems to allow the AutoSizer to get the size just right. 
I tested locally with a layered structure of tables. In Chrome, Safari and Firefox on different screen sizes
=> Fix: DO-1913: table has a weird scrollbar in dara 1 2

borg.toml, lerna.json, packages/create-dara-app/pyproject.toml, packages/dara-components/package.json, packages/dara-components/pyproject.toml, packages/dara-core/changelog.md, packages/dara-core/dara/core/internal/cgroup.py, packages/dara-core/package.json, packages/dara-core/pyproject.toml, pnpm-lock.yaml, poetry.lock, pyproject.toml
Fixes #106 
The issue stems from our usage of the [resource](https://docs.python.org/3/library/resource.html) package for limiting memory usage within containers (which is set with env CGROUP_MEMORY_LIMIT_ENABLED). The package is [unix-specific](https://docs.python.org/3.10/library/unix.html) and is not available for Windows machine.
The `set_memory_limit` util now checks the `sys.platform` const. If it's `win32`, the function emits a warning and immediately returns **before** attempting to import the `resource` package.
Includes patch 1.3.1
Untested due to lack of access to a Windows machine. Future improvement would be having a Windows build in CI that runs at least in some intervals to validate all tests pass on Windows.
=> Fix: DO-1952 `resource` package usage on Windows installations & build 1.3.1

packages/dara-components/changelog.md, packages/dara-components/js/common/label/label.tsx, packages/dara-components/js/common/paragraph/paragraph.tsx, packages/dara-components/js/common/text/text.tsx
Could not set `margin` for a `Text` component
`...style` was applied before `margin` on `Text`, this meant that margin prop, was overwritten by the Text's own styling.
Also took the opportunity to check and fix other places where this might happen
Locally on a test app
=> Fix: DO-1909 cannot set margin for text component

packages/dara-components/changelog.md, packages/dara-components/js/common/input/input.tsx
It was found that when Input of type number was emptied and the user did not enter another number quickly it would crash.
The issue was due to when the NumericInput emptied its value became NaN which was not handled resulting in infinite updates to the point the component crashed. The fix was to handle it by setting to null when empty
Locally on a test version of an app
=> Fix: DO-1953 numeric input breaks when emptied

packages/dara-components/changelog.md, packages/dara-components/js/common/select/select.tsx
Currently, the select component will not display a value if it's not also present in the list of items. This presents a problem when that list of items uses a piece of derived state, which might not be available at the time of render.
This PR lets us explicitly state a `value` of a Select/Multiselect/Combobox, even if it's not in the list of `items`.
If an explicit value is set, it can either be a primitive, in which case it will get converted to an `Item`, or an object, which will be displayed as is.
For the multiselect case, every primitive item in the array will be converted to an `Item` as well.
Locally
=> Improvement: DO-1993: Add explicit value support for Select/Multiselect/Combobox

packages/dara-core/changelog.md, packages/dara-core/dara/core/interactivity/derived_variable.py, packages/dara-core/dara/core/internal/encoder_registry.py, packages/dara-core/tests/python/test_encoders.py, packages/dara-core/tests/python/test_main.py, packages/dara-core/tests/python/test_py_component.py
Previous PR moved the shared arg restoration logic to a central `deserialize` method (previously scattered in DV and py_component logic) as it's now also reused by actions.
It turns out there was a bug there where when the incoming type was already correct (e.g. the type was coming from a derived variable - serverside - or a static kwarg) the deserializer would still attempt to run and fail in some cases.
Several improvements made to the deserializer:
- ensured if `type(value) == type`, skip deserialization
- handle `Optional[foo]` to call `deserialize(value, foo)`
- on failed deserialization, the raw value is returned and an error is logged; this means in case of an error it should still be clear what went wrong and we display an error message
Tested locally on a demo app where the issue …
=> Fix: DO-2004 deserializer running for already serialized values

packages/dara-components/changelog.md, packages/dara-components/js/common/input/input.tsx
When using an input of type number in scenario manager I noticed that it would not load with any value.
The issue was found due to if the variable value became a string in the update then the component could would not show it. The fix was to handle external updates by converting it to a number, in the same way that we do with its own updates.
None
Locally by updating the variable's value through actions
=> Fix: DO-1984 numeric input controlled value

packages/dara-core/changelog.md, packages/dara-core/dara/core/internal/normalization.py, packages/dara-core/dara/core/internal/routing.py, packages/dara-core/dara/core/internal/tasks.py, packages/dara-core/dara/core/visual/dynamic_component.py, packages/dara-core/js/shared/interactivity/use-server-component.tsx, packages/dara-core/js/shared/utils/normalization.tsx, packages/dara-core/tests/js/dynamic-component.spec.tsx, packages/dara-core/tests/js/progress-tracker.spec.tsx, packages/dara-core/tests/js/utils/test-server-handlers.tsx, packages/dara-core/tests/python/test_data_variable.py, packages/dara-core/tests/python/test_derived_data_variable.py, packages/dara-core/tests/python/test_main.py, packages/dara-core/tests/python/test_py_component.py, packages/dara-core/tests/python/utils.py
Dara implements a normalization mechanism, previously used for template response, and requests for DerivedVariables and py_components. This looks for instances of variables, replaces them with references and puts the actual values in a lookup. This decreases payload size in cases where the same variables are referenced in multiple places in a payload, especially when `Variable` has a large `default`.
This was previously not implemented for `py_component` results. A recent discovery in one of the apps was that a response for a particular `py_component` was about 100MB. This was due to the scenario described above, where a `Variable` default was large and duplicated dozens of times, as the component returned a list of cards, each having an action updating that variable. While this to some …
=> Improvement: DO-2030 normalize `py_component` responses

packages/dara-core/changelog.md, packages/dara-core/js/actions/update-variable.tsx, packages/dara-core/js/shared/interactivity/use-variable.tsx, packages/dara-core/tests/js/use-action.spec.tsx
This PR fixes a bug where the update action would not register the updated variable. Simplest way to reproduce would be to have two pages:
- first page updates some variable
```python
target = Variable()
Select(..., onchange=target.sync()
```
- second page uses the variable
```python
Text(text=target)
```
Previously the sync (so the underlying update) action would fail due to the variable not existing on the page yet. This was a regression introduced as part of the action revamp, added a regression test.
Fixed by using similar logic to other actions where the variable is registered if not already registered.
Using the `getOrRegister...` methods within `UpdateVariable` implementation.
Those methods already handle nested plain variables correctly so the implementation was simplified to …
=> Fix: DO-2053 update action not registering variable

packages/dara-components/changelog.md, packages/dara-components/js/common/radio-group/radio-group.tsx
Noticed that when passing an empty Variable to a RadioGroup component in dara the Variable value was never updated.
When Variable was empty this line `items.find((item) => item.value === value)` returned `undefined`.
This meant the `RadioGroup` component behaved in uncontrolled mode and did not trigger on change events. Resulting in the variable never being updated.
Locally on a test app
=> Fix: DO-2052 radio group does not update when starting with an empty var

packages/dara-core/changelog.md, packages/dara-core/dara/core/cli.py, packages/dara-core/dara/core/internal/websocket.py, packages/dara-core/dara/core/main.py
This PR fixes an issue with live reloading happening even without the `--reload` flag on. 
Turns out we've had a bug ever since the `--reload` flag was first introduced (for the curious, internal pre-Dara version commit `0836b23`) where the condition to enable `config.live_reload` was using `os.environ.get("VITE_SERVE_MODE")` which is always truthy, since it's a string `"True"` or `"False"`. This is now changed to check for equality rather than truthiness.
Also fixed an issue where tracking down forced refreshes was difficult due to the errors being emitted into the `eng_logger` rather than `dev_logger`. It's no longer necessary to run Dara with `--debug ERROR` or higher to see the error.
Locally in an app
=> Fix: DO-2136 live reload without --reload flag, move websocket errors to dev_logger

packages/dara-components/changelog.md, packages/dara-components/js/common/anchor/anchor.tsx, packages/dara-core/js/utils.ts
It was found that the Image component does not handle base urls properly, and appends the base url prefix even to external asset URLs.
Similar issue was found with the `Anchor` tag.
The utility used by the Image component now explicitly checks for `/static/` prefix (which is also validated on the backend) and applies the prefixing logic only to those requests.
The anchor component now uses the react router's `Link` component rather than an `<a>` tag for relative links since the router already handles the basename correctly.
Locally in embedded and standard environments
=> Fix: DO-2141 Image and Anchor components base url handling

packages/dara-core/changelog.md, packages/dara-core/js/shared/utils/clean-session-cache.tsx, packages/dara-core/tests/js/template-root.spec.tsx, packages/dara-core/tests/js/utils/mock-storage.tsx
It was found that at some point local storage was running out of space. Seems like we were not cleaning up session related values.
Added so that we clean session related objects from Local storage.
Locally by using `Variable`s with persist flag and checking that storage was cleaned after log out/log in
Also updated a test for cleaning cache. Before it falsely succeeded due to waitFor not being properly awaited.
=> Fix: DO-2171 cleanup of local storage

packages/dara-core/changelog.md, packages/dara-core/dara/core/interactivity/any_variable.py, packages/dara-core/dara/core/internal/devtools.py, packages/dara-core/dara/core/internal/registries.py, packages/dara-core/dara/core/internal/routing.py, packages/dara-core/dara/core/internal/websocket.py, packages/dara-core/dara/core/main.py, packages/dara-core/tests/python/test_websocket.py
Currently, we treat web socket channels as a one-to-one relationship with the session. This works okay for most cases, but if we have two web socket channels for the same session(i.e. a different tab) values of the variables are lost as they are tied to the web socket channel.
- Added a `WS_CHANNEL` context var to websocket -- this is setup to get the actual variable on the actual channel
- Added functionality on `get_current_value` to get the current value on the channel if the channel is provided, otherwise, we get the value from all the channels.
- Changed the session_channel list to be a `Set` since one session can have multiple channels
- Trickled down session error to all channels
N/A
This has been tested locally and also by unit tests.
=> Fix: DOS-479 Added support for multi websocket channels

packages/dara-core/changelog.md, packages/dara-core/dara/core/cli.py, packages/dara-core/dara/core/js_tooling/js_utils.py
In prod mode, sometimes we want to skip the JS building process as the js assets already exist.
Add skip-jsbuild flag, if user run `poetry run dara start xxx --skip-jsbuild`, will skip building js assets
No
locally tested
=> Feat: DO-2312 Add skip rebuild flag

packages/dara-core/changelog.md, packages/dara-core/dara/core/interactivity/any_variable.py, packages/dara-core/tests/python/test_websocket.py
Resolves an issue that caused variables to break when fetching their current value after the user navigates away and back to the application.
* Address the websocket session not being configured correctly in get_current_value after navigating away and back to a running kernel
* The double if block ended up with a situation where the sessions could be empty even though a session existed which lead to the request failing even though there was a connection to use.
No
Tested Locally
=> Fix: DOS-577 Address failure of get_current_value

packages/dara-components/changelog.md, packages/dara-components/dara/components/plotting/bokeh/bokeh.py, packages/dara-components/js/plotting/bokeh/bokeh.tsx
When container surround `Bokeh` had `hug` set to `True` and figure had `sizing_mode` set to `scale_both` or similar then the plot would not be visible.
Updated so that `Bokeh` will have `min-height` and `min-width` set in line with `Plotly` in those scenarios.
By default if the user does not do anything with `Bokeh` it will have a fixed size on the page, as figure does.
If they set any other height within the figure that will still be respected, but if that value is smaller than the `min_height` of 350px the user would have some leftover space unless they updated this value on the `Bokeh` component itself and not the figure.
None
Locally on a test app
=> Improvement: DO-2402 add min height to bokeh component

packages/dara-core/changelog.md, packages/dara-core/dara/core/internal/import_discovery.py, packages/dara-core/dara/core/internal/routing.py, packages/dara-core/dara/core/internal/websocket.py, packages/dara-core/tests/python/test_import_discovery.py
It was reported that import discovery can take a long time (20s+) to resolve the imports.
Initial investigation found that the same modules were repeatedly recursed into which caused unnecessary work to be done.
The discovery is a recursive process which avoids infinite recursion by keeping a list of already encountered symbols. 
To illustrate the issue consider the following scenario:
Let's consider three modules: `MainModule`, `SubModule1`, and `SubModule2`. Assume that `SubModule1` defines `SymbolA` component, and `SubModule2` defines `SymbolB` component and also imports `SymbolA`. Both components from sub-modules are imported into `MainModule`. 
Previously, separate ignore lists are created for each `run_discovery` call, leading to `SymbolA` being processed multiple times (diagrams …
=> Fix: DO-2407 make import discovery re-use the same ignorelist to not consider a given symbol more than once

packages/dara-core/changelog.md, packages/dara-core/js/shared/dynamic-component/dynamic-component.tsx, packages/dara-core/tests/js/dynamic-component.spec.tsx
Current behaviour of `suspend_render` was to only apply it to a specific component. This resulted in not-so-great DX as it often needed to be repeated on children of a given component when the behaviour was desired for the entire sub-tree.
The behaviour is now changed in that the setting is now inherited and applied "recursively" to an entire sub-tree, i.e. all children, grandchildren and so on of a given component. This is technically a change in behaviour but since it's a rather advanced feature and the new behaviour is more desirable, we can release it in a minor/patch as it shouldn't be breaking.
This is implemented by hooking into the FallbackContext in DynamicComponent. The value provided to the context is now taken from the parent context value, if present and not overriden by the …
=> Improvement: DO-2342 inherit suspend_render setting

packages/dara-core/changelog.md, packages/dara-core/dara/core/internal/execute_action.py, packages/dara-core/dara/core/internal/routing.py
* An internal project was stalling requests when multiple actions were in flight that led to the app appearing broken for a time until the first action completed.
* The usage of BackgroundTasks in the new execute_action code was found to be causing blockages of new requests being picked up by the event loop. I think this maybe a reccurance of https://github.com/encode/starlette/issues/919 which they claim is resolved, but still doesn't appear to be working for us. It may be due to one of our middlewares behaving in a particular way that causes this, but the fix applied here appears to be the simplest fix for now.
* In this instance we have replaced the usage of background_tasks.add_task with asyncio.create_task that will run the task in the loop without worrying about its result.
No …
=> Fix: DOS-625 Address action execution blocking new requests

packages/dara-core/tests/python/test_data_variable.py
Address the flaky test when running in CI
Use wait_assert to wait for the call to be processed rather than expecting it to be called immediately.
No
Needs to be tested in CI as it passed everytime locally.
=> Fix: DOS-625 fix the test that became flaky on CI after recent change to action execution

packages/dara-core/js/shared/interactivity/store.tsx
DerivedDataVariable get_current_value function can't not find the uid.
Check if key exists in selectorFamilyRegistry.
No
Locally tested
=> Fix: DO-2510 DerivedDataVariable get_current_value not working

packages/dara-core/changelog.md, packages/dara-core/dara/core/cli.py
Currently Dara makes a rudimentary check if `Node.js` is installed if it knows it will be required later, e.g. in `production` mode.
Recently we introduced an explicit `--skip-jsbuild` flag which assumes assets are prebuilt. There was an oversight that even with that flag on, Node was still required
Skipped Node version check if `--skip-jsbuild` was passed.
Manually verified correct behaviour locally
=> Fix: DO-2522 skip Node check if `--skip-jsbuild` is used

packages/dara-components/changelog.md, packages/dara-components/dara/components/plotting/plotly/themes.py
x=0 and y=0 lines on Plotly had no color by default which could look weird
Added a default zeroline color to our Plotly theme of grey3 of our palette
None
Locally on light and dark themes
Light theme
Dark theme
=> Improvement: DO-2465 zerolinecolor on plotly theme should be grey 3 by default appears white

packages/dara-core/js/api/websocket.tsx, packages/dara-core/js/shared/template-root/template-root.tsx
Found this issue whilst debugging studio being unresponsive after being left for a while on another tab.
* If the websocket client is closed for some external reason, e.g. browser going to sleep or a crash being thrown down it then the newly created websocket client is now properly reconnected to all the relevant streams and channels.
No
Tested Locally in a running studio instance
=> Fix: DOS-649 Properly recreate the websocket client when it is closed

packages/dara-core/changelog.md, packages/dara-core/js/shared/variable-state-provider/variable-state-provider.tsx
Tracing a bug that caused all the pick variables to break I discovered this issue with the VariableStateProvider component.
* If errors are not caught here then a single crash takes down this stream handling completely and no more requests for variable values are processed.
* As these requests can sometimes involve reaching out to a backend then this code should be resilient to faults and not break the behaviour of the app for subsequent requests.
No
Tested Locally
=> Fix: DOS-649 Catch errors thrown in the variable state provider

packages/dara-core/changelog.md, packages/dara-core/js/shared/interactivity/plain-variable.tsx, packages/dara-core/tests/js/persistence.spec.tsx
Edge case found when testing latest changes in an internal product.
Since the change in Dara 1.7, when a Variable is registered in a `useVariable` call, a new atom is created per unique set of request extras. This is to enable sending correct request data to BackendStore requests etc.
There was an issue spotted where if a Variable was first registered under a given set of extras, updated, and then registered again under a different set of extras, the second registration would create a new instance which would initialize with the Variable default value rather than the up-to-date value of the first registration.
Fixed by changing the `StateSynchronizer` to also perform an initial `setSelf` on the atom if already registered, using the latest value of a given variable uid.
Internally the …
=> Fix: DO-2551 edge case when registering Variable under different extras

packages/dara-core/changelog.md, packages/dara-core/js/api/websocket.tsx
People were still seeing their instances hang up and after some investigation I found that this was occuring on the second disconnect of the websocket whilst the first recovered fine. This was found to be a small mistake in the previous fix I implemented.
* The previous fix forgot to readd the close handler to the new socket, so another disconnect would leave the socket in the same state as before.
No
Tested in a local instance of studio where a button was added to simulate multiple disconnect/reconnects in a row.
=> Fix: DOS-727 address the disconnect of the websocket on subsequent disconnects

packages/dara-core/dara/core/persistence.py, packages/dara-core/tests/python/test_persistence.py
When testing the store more locally I noticed the default value is not applying correctly. It is an unexpected behaviour as the tests are passing in that regard; tracking down the issue with logs revealed that somehow modifying the store `_default_value` in the init phase was not 'saved' in the model state and later default values were set as `None`.
I tried switching the `PrivateAttr` to a normal `Field` and the bug went away, though I also had to remove the underscore prefix from the field names. Not sure why it worked that way but it might be a Pydantic quirk.
Added a custom constructor to prevent the fields from being initialized or showing up in the inspection.
Locally
=> Fix: DO-2535 use non-private fields for backendstore

Makefile, packages/dara-core/changelog.md, packages/dara-core/dara/core/main.py, packages/dara-core/tests/python/test_main.py
* Needed an async startup function for an internal project
* Moves the execution of startup functions to be part of the app lifecycle so we can make allow async function. Detects coroutines being returned and then awaits them.
Unit tests added
=> Fix: DOS-764 Allow async startup functions to be registered

packages/dara-core/changelog.md, packages/dara-core/dara/core/internal/settings.py, packages/dara-core/tests/python/test_settings.py
Currently in Dara when an .env file is missing when attempting to read from environment variables, it attempts to generate one in the CWD. In some cases this directory is not writable. 
This PR changes the behaviour to instead fall back to using in-memory secrets rather than the `.env` file in addition to logging the error.
Try/except added on the env generation logic. In case of failure `_env_file=None` is passed to the `Settings` class as per [Pydantic docs](https://docs.pydantic.dev/1.10/usage/settings/#dotenv-env-support) to make it not attempt to load any files.
The Settings class already as defaults set up for crucial envs like jwt_secret.
Added a unit test to cover the scenario
=> Fix: DO-2651 settings .env file generation failure

packages/dara-core/changelog.md, packages/dara-core/dara/core/persistence.py, packages/dara-core/tests/python/test_persistence.py
Issue discovered with the persistence feature - the store did not respect a preexisting value in the backend.
Initialization logic checks if there is already a value in the store, and only performs a `write` if `has` returned `False`.
Unit tests added
=> Fix: DO-2715 respect existing values in BackendStore backend 

packages/dara-core/dara/core/auth/routes.py
Adding extra logs for auth errors to make debugging future issues easier
Locally, example of an invalid request logs:
```
2024-03-26 13:48:09,797  ERROR  dara.dev  Auth Error
Traceback (most recent call last):
File "/Users/kbiel/code/dara/packages/decision-app/.venv/bin/dara", line 8, in <module>
sys.exit(cli())
File "/Users/kbiel/code/dara/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/Users/kbiel/code/dara/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/Users/kbiel/code/dara/.venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/Users/kbiel/code/dara/.venv/lib/python3.11/site-packages/click/c …
```
=> Improvement: DO-2635 add explicit logs for auth errors

packages/dara-core/dara/core/internal/encoder_registry.py, packages/dara-core/tests/python/test_encoders.py
This bug happens when a `Variable` have a DataFrame and the DataFrame is multi-indexed.
The root reason is that when a df have multiple index, `to_dict()` will use tuple type as key.
However, tuple is not jsonable, hence, jsonable_enocder will turn it into a list. List can't not be used as a key of dict.
To avoid this, when serializing a df, will iterate the dict. If it has a tuple type key, will turn it into a string with a __tuple__ prefix. So the whole dict is jsonable.
However, this require user to  deserialise it, by doing
```
def _tuple_key_deserialize(d):
encoded_dict = {}
for key,value in d.items():
encoded_key = ast.literal_eval(key[9:])if isinstance(key,str)and key.startswith('__tuple__') else key
encoded_value = _tuple_key_deserialize(value) if isinstance(value,dict) else value …
```
=> Fix: DO-2781: Dara serialization: MultiIndex on a pandas.DataFrame

packages/dara-core/changelog.md, packages/dara-core/dara/core/internal/websocket.py, packages/dara-core/js/api/websocket.tsx, packages/dara-core/tests/python/test_websocket.py
* An internal project needs to send back a bunch of data in reponse to a websocket message and it doesn't all fit within a single response, so this change adds the ability to chunk responses.
* Adds the ability to pass a chunk_count parameter along with DaraClientMessages to denote that there are multiple parts to this message that will be sent separately.
* On the backend side we then wait for the specified number of messages to be received before setting the event to unblock the sendAndWait handler. We make no attempt to recombine the messages on the backend at this time as we don't know what format the response will be in on the framework side. It's left up to the calling code to know when chunked responses might be returned and handle the merging appropriately.
* A new api …
=> Fix: DOS-887 Add chunking of websocket messages

packages/dara-core/dara/core/internal/encoder_registry.py, packages/dara-core/tests/python/test_encoders.py
The previous deserialise method will turn tuple to ["'mean'", "'median'"] instead of  ["mean", "median"]
For each string, will split by `,` first, then check it the result start and end with `'` or `"`, if so, remove it. 
No 
Integration tested
=> Fix: DO-2781 Fix multiple index df deserialization

packages/dara-core/changelog.md, packages/dara-core/js/api/websocket.tsx, packages/dara-core/package.json, packages/dara-core/tests/js/websocket.spec.tsx, pnpm-lock.yaml
* The existing logic for retrying when the websocket connection fails lead to it looping forever when trying to reconnect due to faulty logic that lead to multiple sockets being created and the number of attempts always being 0 so never hitting the max count.
* My previous changes had also not gone far enough in terms of updating the global socket variable that left this code in an odd state after a reconnection. For example, new connections did not get a proper heartbeat setup as this was done on the global level.
* To address this, I've moved all the socket connection logic to the initialize function, this is now where the socket is created and has all it's listeners attached. Calling this function will create a brand new socket everytime with all the correct handlers rather than the …
=> Fix: DOS-913 Websocket Reconnection Refactor

packages/dara-components/changelog.md, packages/dara-components/js/smart/chat/chat.tsx
On an app that had 14px base font size instead of the default 16px, the chat icon appeared off centre
The issue was that the svg of the icon was in px size, whereas the height/width and padding of the button used rem. That meant that it causeed it to appear off centre.
Being a fixed icon button I thought it made more sense to make it all px, so the values have been updated accordingly.
None
Locally on apps of both 16px and 14px base font sizes
=> Fix: DO-2958: chat icon off center for different base rem

packages/dara-components/changelog.md, packages/dara-core/changelog.md, packages/dara-core/js/api/websocket.tsx, packages/dara-core/tests/js/websocket.spec.tsx
* Found more bugs with the reconnection logic that reconnected the streams properly, but no messages could be sent back which broke most things.
* Previous change was refactored late on to have initialize return the new socket rather than setting it. This was not properly applied in the reconnect logic so we ended up with the stale socket on the class so no messages could be sent.
No
Unit test extended to cover it
=> Fix: DOS-1010 Fix the websocket reconnection so this.socket is correct

packages/dara-components/dara/components/common/checkbox_group.py, packages/dara-components/dara/components/common/radio_group.py
It's been reported that CheckboxGroup does not work properly in a following scenario:
```python
from dara.core import Variable
from dara.components.common import CheckboxGroup
from dara.components import Item
item1 = Item(value=1, label='foo')
item2 = Item(value=2, label='bar')
CheckboxGroup(
items=[item1, item2],
value=Variable([item1]),
)
```
It turns out this example works if we change the following:
```
CheckboxGroup(
items=[item1, item2],
-    value=Variable([item1]),
+    value=Variable([1]),
)
```
This is a matter of a missing example in the docstring. The behaviour is consistent with other Select and Radio components - the `value` prop keeps track of the `value` selected, not the entire item. 
This PR fixes the CheckboxGroup and RadioGroup docs to correctly show this behaviour in …
=> Fix: DO-2768 checkbox group and radio group docs

packages/dara-components/changelog.md, packages/dara-components/js/common/select/select.tsx
Just like `Select`, it was intended that select with `multiselect=True` should display its `value` as a fallback even when the items are not in the `items` list.
There was a minor bug which caused the effect to wipe the selected items after the initial render.
Locally
```py
config.add_page('test', Select(multiselect=True, items=Variable([]), value=Variable(['one'])))
```
https://github.com/causalens/dara/assets/87647189/72971883-0f52-4c56-9eee-f3992bb56997
=> Fix: DO-3014 multiselect value outside of items

packages/dara-core/changelog.md, packages/dara-core/dara/core/interactivity/derived_data_variable.py, packages/dara-core/tests/python/test_derived_data_variable.py
It's been reported that in some cases DerivedDataVariable (DDV) can be invoked with a `PendingValue`, an internal Dara store value which represents a started computation. Upon investigation, this could happen in a scenario such as:
- a DDV computation is invoked and finished, resolving to a cache key to query data from
- another computation is invoked for the same set of inputs
- while the second computation is ongoing, a query for the data is made against the cache key
This caused the data query to retrieve a `PendingValue` from the store which was inserted there by the second computation. 
The fix was to handle that case and await the computation resolution.
As part of the investigation I spotted another issue where a cache eviction could get 'inbetween' the derived and query parts of …
=> Fix: DO-3050 DerivedDataVariable leaking PendingValue to userspace

packages/dara-components/changelog.md, packages/dara-components/js/common/input/input.tsx, packages/dara-components/js/common/textarea/textarea.tsx
Issue reported in an internal product that state does not behave as expected. After investigating the issue, I noticed the `onchange` action did not fire at all for an Input component. 
Looking for similar code in other components, the same logic applied in `Textarea` so I applied the fix there too. 
The reason why this regressed now is I think due to #319. There we changed simple Variables to no longer go through a deferred layer which made the state update a tick later (in an effect). This made the current, buggy code work and the recent change unveiled the bug.
Digging deeper I spotted that the action was being scheduled as a debounced call but then immediately cancelled by an effect.
The fix was to simply not cancel scheduled debounced action calls to prevent these issues from …
=> Fix: DO-3214 input not firing `onchange` action

packages/dara-components/changelog.md, packages/dara-components/js/common/input/input.tsx
Issue was found when emptying a numeric input. Its value as stored in the variable was `None`, whereas in an action `ctx.input` returned `NaN`. 
We convert the value based on whether the input is numeric, however we were not passing this new value to the action
None
Locally
=> Fix: DO-3172 numeric input none value is inconsistent

packages/ui-components/docs/changelog.md, packages/ui-components/src/chat/chat.stories.tsx, packages/ui-components/src/chat/message.tsx, packages/ui-components/src/code-viewer/code-viewer.tsx, packages/ui-components/src/markdown/markdown.tsx
Improve the visuals of code blocks rendered within `Chat` component, and allow users to easily copy its content
~~Added a parser that breaks the message string into `Markdown` and `CodeViewer` components. This is only applied to the displayed message so that when editing users still have full control of the markdown string and can make changes if needed~~
Updated base markdown component to use `CodeViewer` for code blocks with a specified language.
Locally on storybook
=> Feat: DO-3456 extract code from markdown and use code viewer in chat component

packages/dara-components/changelog.md, packages/dara-components/tests/python/utils.py, packages/dara-core/dara/core/interactivity/derived_data_variable.py, packages/dara-core/dara/core/internal/routing.py, packages/dara-core/js/shared/interactivity/data-variable.tsx, packages/dara-core/tests/python/test_data_variable.py, packages/dara-core/tests/python/test_derived_data_variable.py, packages/dara-core/tests/python/test_pandas_utils.py
The param was being sent as a body which is not allowed for a GET request.
=> Fix: DO-3494: Make Table schema cache_key a query param

packages/dara-core/dara/core/internal/registry_lookup.py
When an entry is not found in the registry, we execute the handler to get the result and register it. While we execute the handler, something else might already register that specific entry, so before explicitly registering it again and getting an error we check it and only register it if it's still missing. Since registry is a dict, both `.get` and `.register` are atomic.
=> Fix: DO-3494: Fix race conditon in registry entry registration

packages/dara-core/changelog.md, packages/dara-core/dara/core/interactivity/filtering.py
-   Fixed a crash in `Table` pagination where rows containing non-unique index values would cause a slicing error, as rows were paginated by DataFrame index instead of `iloc` row ordering.
-   Fixed an issue in `Table` where sorting by an unnamed index would not work, as the default `__index__` unnamed index column does not exist in the original DataFrame.
=> Fix: DO-3658: Fix Table non-unique index values, fix sorting by unnamed index

packages/ui-causal-graph-editor/changelog.md, packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx
In some cases where you had a `CausalGraphViewer` next to a `Card` it would render with 0 width, making it confusing for users to understand that it was there and how to fix it.
Similarly to how we do for height, added a `min-width` of `100px`, just so it renders with something, from there it is easy for a user to update this value if needed.
None
Locally
=> Fix: DO-3770 add min width to causal graph viewer

packages/dara-components/changelog.md, packages/dara-components/js/common/table/table.tsx
User found that with their dataset the timestamp column showed with dates in 1970s whereas when printing with pandas these were correctly inferred to be in 2023.
It seems that in this case the column had timestamps in seconds. When we tried to get the corresponding dates with `formatISO` we assumed the timestamp is given in ms. I have updated this to now consider that the timestamp might be in seconds or nanoseconds and convert accordingly.
Limitations with this approach:
- If dates go beyond the year 33658 then dates would be wrongly inferred as ms will reach 1e15 and seconds reach the ms range. This seems unlikely for vast majority of what might be fed to the table component, so seemed like an ok assumption.
- We also don't take into account microseconds. I don't think it is that …
=> Fix: DO-3828 table showing wrong dates

packages/ui-components/changelog.md, packages/ui-components/src/numeric-input/numeric-input.spec.tsx, packages/ui-components/src/numeric-input/numeric-input.stories.tsx, packages/ui-components/src/numeric-input/numeric-input.tsx
User found that if they type `10.` and then tried to backspace, then it didn't go to `10`
The issue was found that when we updated the input to `10.`, we keep the value at `10`, so when the backspace is pressed the value does go to `10`, but since the value hadn't changed then the useEffect was not triggered and so the input was not updated.
None
Locally on storybook and by adding a test
=> Fix: DO-3869 input component bug

packages/ui-causal-graph-editor/changelog.md, packages/ui-causal-graph-editor/src/shared/rendering/edge/edge-object.tsx, packages/ui-causal-graph-editor/src/shared/rendering/engine.tsx, packages/ui-causal-graph-editor/src/shared/rendering/node/node-object.tsx
Multiple users reported that sometimes the nodes and edges of their graph would disappear. But after interacting with the graph they magically appeared again.
The issue was found to be related to [this issue](https://github.com/pixijs/pixijs/issues/10735) on Pixijs.
When a node was added or the graph was resized, the node could temporarily be positioned outside the visible frame. This occurred either because a newly created node did not yet have a defined position or because resizing the graph to a smaller size pushed existing nodes outside the frame. As a result, the nodes were being prematurely culled and rendered invisible before reaching their final render state.
The fix was added to `updateLayout`, as this method is called in both scenarios where the issue occurred. The solution …
=> Fix: DO-3956 causal graph viewer not updating nodes when graph is updated

packages/dara-components/changelog.md, packages/dara-components/js/plotting/plotly/plotly.tsx
Issue found in internal product where when setting height on a figure layout that the resulting plot did not have correct height.
Internal product uses dara's `Plotly` component under the hood. The fix was aimed at improving this for both dara apps and the internal product. 
Since dara uses an Autosizer around plotly any height set within the component was being ignored and the autosizer value replaced it. In order to improve the behaviour to be able to set `height` as both part of the figure layout and prop to the component, I added a style to check if figure has this set and if so to use it instead. The order of preference becomes:
1. Height/width set to Plotly component
2. Height/width set to Plotly figure
3. Use autosizer
None
Locally on a dara app and by testing these changes in the …
=> Fix: DO-3894 native plotly plots cannot change size

packages/ui-components/src/multiselect/multiselect.spec.tsx, packages/ui-components/src/select/select.stories.tsx, packages/ui-components/src/shared/dropdown-list.tsx, packages/ui-components/src/shared/list-item.tsx, packages/ui-components/src/types.tsx
* Add the display of icons to dropdown list items (see screenshot below)
Display the icon at the end of the row if it's present, expects any JSX element.
No
Locally in storybook
=> Fix: DO-4169 Add icon display to dropdown items

packages/dara-core/changelog.md, packages/dara-core/js/api/websocket.tsx, packages/dara-core/js/shared/global-state-store.tsx, packages/dara-core/js/shared/template-root/template-root.tsx, packages/dara-core/tests/js/template-root.spec.tsx, packages/dara-core/tests/js/utils/mock-storage.tsx, packages/dara-core/tests/js/utils/mock-web-socket-client.tsx
Issues seen in local dev with the messaging locking up, changes to the websocket client not getting propogated after a token refresh. This change also resolves the stale token issue on websockets where when there was a single tab the context var was set incorrectly.
* There was a misunderstanding in how the storage event worked that led to single open tabs not correctly refreshing their tokens when required. This is due to the event only being fired when storage is changed from another document. This meant that the session token in the useSessionToken hook was not correctly updated in the current tab.
* To address this the local subscribers field is now used again (it was left in a broken state, but not completely removed) and correctly pushes out updates to a key to all local subscribers …
=> Fix: DO-4274 fix a couple of issues in the token refresh logic around websockets

.github/workflows/tests.yml, packages/dara-core/changelog.md, packages/dara-core/dara/core/internal/websocket.py, packages/dara-core/js/api/websocket.tsx
Address Studio being broken after coming back to it after leaving the tab for a while.
* There were two issues causing this. The first was that we were raising HTTPExceptions rather than Websocket exceptions during the handshake and upgrade from http request to websocket. This caused the error to be swallowed and replaced with a generic error log and handshake failed response.
* Switching to using WebsocketException now gets properly handled and the logs now correctly show the 403 exception and logged detail rather than swallowing everything.
* The second part of the issue was that the websocket client on the JS side was getting stuck with a stale token if this happened whilst the computer was sleeping / tab sleeping. I suspect this was caused by updateToken trying to send a message on …
=> Fix: DO-4864 Resolve websocket not reconnecting correctly.

packages/dara-core/dara/core/internal/routing.py, packages/dara-core/dara/core/internal/websocket.py, packages/dara-core/dara/core/persistence.py, packages/dara-core/js/shared/interactivity/persistence.tsx, packages/dara-core/tests/js/persistence.spec.tsx, packages/dara-core/tests/python/test_persistence.py, packages/dara-core/tests/python/test_websocket.py
When using the `BackendStore` persistence for `Variable`s, the user who caused the update would also receive a WS message about the change. This would cause potential race conditions and state desyncs where if the variable changes multiple times while an update is being sent to the backend, the client can then get set 'back in time' after they receive a delayed notification about their own update.
This is especially noticeable on slower connections and when storing objects in the variables (as Recoil might skip updates for same primitive values).
Added `ws_channel` parameter to the request for `POST /api/core/store`. We then set the context var `WS_CHANNEL` before invoking `store.write()`.
Inside the backend store notification logic, we pass the current `WS_CHANNEL` into the websocket …
=> Fix: DO-5316 originating WebSocket channel being notified about their own variable updates

packages/dara-components/changelog.md, packages/dara-components/js/plotting/plotly/plotly.tsx
Similar to our previous Plotly issues (e.g. https://github.com/causalens/dara/pull/140).
When putting it into a Stack without setting an explicit size, it tries to fill its parent using the AutoSizer and following flex rules. When using an `align-items` property on its flex parent other than `stretch` (the default), the component shrinks to its minimum size.
For horizontal Stacks, we had a `minHeight` set to 350 by default to prevent it disappearing completely.
The component was missing a matching `minWidth` which was causing it to disappear in a vertical stack with align other than `stretch`.
Added default min-width. It can be overridden by the user just like the height.
Locally in a test app. See behaviour of different alignments of the parent flex:
Vertical: …
=> Fix: DO-5476  Plotly component disappearing in vertical stacks when overriding `align-items`

packages/dara-components/changelog.md, packages/dara-components/dara/components/common/slider.py, packages/dara-components/tests/python/common/test_slider.py, packages/ui-components/src/slider/slider.tsx
Issue reported when with a specific configuration the slider would 'move on its own', i.e. constantly readjust its tracks.
The reported configuration was `domain=[31635, 70876] values=[31635, 70876]`. 
The component has validation for step/domain compatibility (i.e. the range must be divisible by the step) but it was only verified when both were provided. The Slider can operate with an inferred step (i.e. only domain is provided) but then we wouldn't validate it.
This PR adds additional validation on the backend to run a similar step inference and cross-validate it with the domain and thus fail early.
Now the same reported scenario simply raises:
```
(...)
pydantic.error_wrappers.ValidationError: 1 validation error for Slider
step
Step 1000 (inferred from domain range) is not compatible …
```
=> Fix: DO-5467 slider moving on its own

packages/dara-components/changelog.md, packages/dara-components/dara/components/graphs/components/edge_encoder.py, packages/dara-components/tests/python/graphs/test_edge_encoder.py, packages/dara-core/changelog.md, packages/dara-core/dara/core/interactivity/plain_variable.py, packages/dara-core/dara/core/internal/encoder_registry.py
Issues reported around serializing visual edge encoder. The `nodes` type can include `cai_causal_graph.graph_components.Node` type (or a `dict[str, Node]` to be precise) which is not serializable by default.
To improve it I applied the following:
- `Variable.default` now uses `jsonable_encoder` with custom encoders using our registry, which now also handles cases where the serializable type is within a dict/list/one of the known serializable containers
- added a `field_serializer` to `VisualEdgeEncoder.nodes` to handle serializing the type explicitly
- added a serializer for `Node` to encoder registry
Locally using different combinations of CausalGraph.Node with edge encoder:
```python
VisualEdgeEncoder(
nodes=['Age', 'Unemployment', 'Education', 'Income'],
...
),
VisualEdgeEncoder( …
```
=> Improvement: DO-5864 improve `Variable.default` serialization, add serializers for `VisualEdgeEncoder.nodec` and the `cai_causal_graph` `Node` type

packages/dara-core/changelog.md, packages/dara-core/dara/core/base_definitions.py
Issue came up in pydantic v2 migration: Derived fields in `ActionImpl` require explicit serialization in user-land.
This PR marks every derived field in `ActionImpl` to be automatically serialized by `jsonable_encoder`.
Locally.
=> Improvement: DO-5991: Improve serialization of `ActionImpl` to automatically serialize nested fields

packages/dara-core/changelog.md, packages/dara-core/dara/core/js_tooling/js_utils.py
Fix dev mode apps not loading correctly
The alteration to the base url in the vite config broke the development server. There doesn't appear to be a way to change the base url from the config so it needed to be applied in the dev command inserted into the package.json.
The alternate way that did not work was to leave the dev server serving on / and try to update the static path to "". Doing this seems to default back to /static/ though and setting it as / caused double // in a couple of places that broke other things.
No
Tested locally in studio
=> Fix: DO-6035 Fix for dev mode after the previous static url changes

packages/dara-core/changelog.md, packages/dara-core/js/auth/auth.tsx, packages/dara-core/js/shared/private-route/private-route.tsx, packages/dara-core/tests/js/auth.spec.tsx
* The base_url wasn't being handled correctly when setting the referrer into state for redirection. This caused the path part of the base_url to be duplicated on redirect.
* Added a resolver function that adjusts the referrer based on the base_url.
* Adds a test to check it's working correctly.
No
Unit test added
=> Fix: DO-6306 Patch dara referrer handling when a base_url is set

Makefile, packages/dara-core/changelog.md, packages/dara-core/dara/core/internal/routing.py, packages/dara-core/dara/core/persistence.py, packages/dara-core/js/shared/interactivity/persistence.tsx, packages/dara-core/package.json, packages/dara-core/tests/python/test_persistence.py
Previously we had ignore_current_channel for all notifications to prevent loopbacks.
This now causes an issue with partial updates, where the user needs to specifically set `WS_CHANNEL.set(None)` before a `write_partial` to repaint the UI.
Now that we're also checking for `STORE_LATEST_VALUE_MAP` on the client, we can ignore only the `write` part in `sync_backend_store`, removing `ignore_current_channel` and the need to reset WS_CHANNEL.
Also fixes an issue where the first read after a browser refresh was sending another write on the client, un-syncing the sequence numbers.
Demo app, fixed tests
=> Improvement: DO-6672 Prevent BackendStore loopback on write, Remove ignore_current_channel, Fix first read

packages/dara-core/changelog.md, packages/dara-core/dara/core/definitions.py, packages/dara-core/tests/python/test_components.py
Regression caused by prior release, passing raw_css as explicitly None would fail validation.
Adjusted validation
Added regression test, failed before but passes now
=> Fix: DO-6799 component instance fails validation when raw_css=None

packages/dara-core/changelog.md, packages/dara-core/js/shared/utils/use-component-styles.tsx
Issue with `raw_css` set to a Variable that resolves to a dict. Caused by missing memo dependency.
Tested by modifying the JS in a local app where the issue was found
=> Fix: DO-6799 raw_css set to a Variable with dict styles wouldn't update

packages/dara-core/changelog.md, packages/dara-core/js/shared/template-root/template-root.tsx
The websocket in dara was being force closed and not recreated when the token refreshed. Removing the force closure resolves the issue. @krzysztof-causalens I'm not sure exactly what the reason for adding the closure was in the first place, so perhaps this breaks something else? 
* Removed the forced closure of the websocket on token change. The structure of the hook meant that the first time the token changed it would close the existing websocket but not recreate it. This permanently bricked the WS connection and the app would appear to hang anywhere that used actions or derived vars.
No
Tested Locally
=> Fix: DO-6904 fix token refresh handling

packages/dara-core/changelog.md, packages/dara-core/js/shared/interactivity/url-variable.tsx, packages/dara-core/pyproject.toml, packages/dara-core/tests/python/test_pool.py
In some convoluted scenarios where URLVariables were being rendered within e.g. py_components, they would sync their default value instead of reading from URLs.
To circumvent that, I found that flipping `syncDefault` back to false fixes the issue.
This changes the behaviour slightly in that the default value doesn't immediately end up in the query params. This might be for the better though as it pollutes the user's url bar less. Passing a default value in the url bar still works, it's just not synced up.
Locally in a reproducible scenario
https://github.com/user-attachments/assets/36e214ee-1b32-4644-b0f8-6905ef3f77b1
=> Fix: DO-6971 UrlVariables being wiped

docs/advanced/loading-states.md, packages/dara-core/changelog.md, packages/dara-core/js/shared/interactivity/condition-or-variable.tsx, packages/dara-core/js/shared/interactivity/switch-variable.tsx, packages/dara-core/js/shared/interactivity/use-any-variable.tsx, packages/dara-core/js/shared/interactivity/use-variable.tsx, packages/dara-core/js/shared/utils/use-defer-loadable.tsx
A quirk of the reactivity system of Dara was that components that are meant to be purely client-side and help users avoid backend roundtrips and thus excessive spinners, didn't quite achieve that:
The `If` component and `SwitchVariable`, when used together with a `DerivedVariable` as the Condition, would suspend the entire `If` component (in the former case) or the component consuming the switch (in the latter) on every computation change.
This PR changes those so that they behave as if `suspend=False` setting was set on them. This means that while they will suspend for the initial computation (unavoidable), further changes will choose to tear rather than suspend - use the prior state while a new one is computed.
Users can choose to use py_components instead if they want to opt into …
=> Improvement: DO-6963 don't resuspend components on DerivedVariable change in If and SwitchVariable

packages/dara-components/changelog.md, packages/dara-components/js/common/select/select.tsx, packages/ui-components/changelog.md, packages/ui-components/src/sectioned-list/sectioned-list.tsx
The `onInputValueChange` in the sectioned-list component was getting triggered and updating the selected input even on state change event types like `__menu_mouse_leave__`, resulting in sometimes the `selectedItem` being overwritten.
The `Select` component supports the `placeholder` prop but this is not passed along to the `SectionedList` select component 
- Updated the `onInputValueChange` to only update the `InputValue` on `InputChange` and `ItemClick` state change events, allowing for selectedItem to only change when searching or actually clicking a new selected item.
- Passed the placeholder prop to the `SectionedList` component and updated logic accordingly to fallback to it.
No
Manually
https://github.com/user-attachments/assets/b53b6173-a60e-443d-9a9d-4f75ea689376 …
=> Fix: DO-7216 - SectionedList on-change bugfix and placeholder support

packages/dara-core/changelog.md, packages/dara-core/js/pages/route-error-boundary.tsx, packages/dara-core/js/shared/interactivity/persistence.tsx
Two issues found:
- the top-level route error boundary would fail to render because it's outside the main theme provider - added an extra default theme provider for it to handle
- the above uncovered a race condition where if loader data was a promise (can be for PageRoutes) we wouldn't properly await it - fixed the typing and awaited it there properly
Locally in an app where this reproduces
=> Fix: DO-7486 handle loader data being a promise

packages/dara-core/changelog.md, packages/dara-core/cypress/integration/state_variable.ts, packages/dara-core/js/shared/interactivity/derived-variable.tsx, packages/dara-core/js/shared/interactivity/plain-variable.tsx, packages/dara-core/js/shared/interactivity/store.tsx, packages/dara-core/js/shared/utils/hashing.tsx, packages/dara-core/tests/js/use-variable.spec.tsx
Issue found in an internal app. Creating a DerivedVariable and using it with different `.get()` calls, i.e. nested values, would result in multiple fetch calls which wouldn't reuse our route loader precomputed values.
Issue was architectural. Previously the flow for DerivedVariables was:
1. 'result selector' that resolved dependencies and returned an entry for 'current' (i.e. must recompute/fetch value), 'previous' (i.e. can just return a cached value) or 'cached' (i.e. must await cached deferred value and then resolve it).
2. 'selector' that resolved the entry from step 1, handled task fetching, and ultimately **handled nested values** and set the **final** result back to the cache registry
This was problematic as we treated each variable with 'nested' differently rather than …
=> Fix: DO-7796 nested DerivedVariable handling causing multiple computations
