.github/workflows/publish_docs.yml
.github/workflows/release.yml
.github/workflows/tests.yml

Should fix the tests along with some updated secrets 🤞 
Setup a new artifactory repo for the base image alone so we don't expose any internal stuff by accident
No
Tests running on this PR will confirm it's working

Fix: DOS-83  Update the repos to point to docker-open-source which just contains the base image for now

---

docs/sidebar.json

rename best practices to design guidelines for clarity

Docs: DO-1629 rename best practices

---

docs/faq.md

The motivation behind this change is for the matplotlib faq about usage of Figure be more discoverable.

Docs: DO-1637 update matplotlib faq to be more generic

---

docs/advanced/custom-js.mdx
packages/dara-core/changelog.md
packages/dara-core/dara/core/__init__.py
packages/dara-core/dara/core/cli.py
packages/dara-core/dara/core/configuration.py
packages/dara-core/dara/core/internal/devtools.py
packages/dara-core/dara/core/internal/registries.py
packages/dara-core/dara/core/internal/tasks.py
packages/dara-core/dara/core/internal/websocket.py
packages/dara-core/dara/core/js_tooling/js_utils.py
packages/dara-core/dara/core/main.py
packages/dara-core/js/api/websocket.tsx
packages/dara-core/js/index.tsx
packages/dara-core/tests/python/test_tasks.py
packages/dara-core/tests/python/test_websocket.py

Support use cases where custom JS components need to utilise the WebSocket connection for better performance, i.e. real-time updates. Further context in Jira ticket.
This PR extends the WS system to support a new type of WS messages (both client and server side), a 'custom' message. The message format has a 'kind' attached to it, which the Python code, and the JS component can choose to handle. 
The API on the Python side looks as follows:
```python
config.add_ws_handler(kind, handler)
```
Behind the scenes the handler is added to an in-memory registry at server startup. When a custom message is encountered, the WS handling logic looks up a handler for the given kind and executes it. If the handler returns a value (other than None), a WS message is sent back with the same `kind`. 
In …

Feat: DO-1503 support custom WebSocket messages

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Build:1.0.1

---

packages/dara-components/dara/components/graphs/components/edge_encoder.py

The documentation for VisualEdgeEncoder was missing an example for `initial_constraints`

Docs: DO-1655 Improve docs for visual edge encoder

---

.github/workflows/publish_docs.yml
.github/workflows/release.yml
Makefile
tooling/scripts/docs-upload.py

Docs were previously built by the internal docs action. Because this repo is now open-source, it cannot use internal (closed source) actions - this is enforced by GitHub and cannot be worked around.
Instead the docs publishing step has been replaced by a script which installs the internal docs parser as a package and manually packages and pushes up the built docs to Artifactory.
The script was added to `tooling`. Necessary steps were added as a Makefile script:
- adding the internal artifactory source to pull `docs_builder` package from
- installing the package
- running the script
`docs_builder` internal package for reference building
Ran the script locally, verified the zip file looks correct

Fix: DO-1658 replace internal docs action with a script

---

.github/workflows/publish_docs.yml
.github/workflows/release.yml
.github/workflows/tests.yml
Makefile
tooling/scripts/docs-upload.py

The publishing script was not working due to the JFrog credentials used in this repo being scoped to open-source repositories.
Fixed by updating the source to point at a new `python-open-source` repository.
Also:
- removed duplicated env creds
- fixed package paths parsing
Tested by adding the workflow step to the TEST workflow, verified it works all the way until pushing the docs (commented out the step) see run here https://github.com/causalens/dara/actions/runs/5854651542/job/15870932485

Fix: DO-1658 docs publishing script not working

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/dara/components/common/select.py
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Making a patch because of a leftover print statement

Build:1.0.2

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Build:1.1.1

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/js/auth/auth-wrapper.tsx
packages/dara-core/js/auth/auth.tsx
packages/dara-core/js/auth/basic/basic-auth-login.tsx
packages/dara-core/js/auth/default/default-auth-login.tsx
packages/dara-core/js/auth/index.tsx
packages/dara-core/js/index.tsx
packages/dara-core/js/shared/index.tsx
packages/dara-core/js/shared/interactivity/use-variable.tsx
packages/dara-core/js/shared/utils/embed.tsx
packages/dara-core/js/shared/utils/index.tsx
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

As part of debugging auth issues in embedded environments (i.e. inside an iframe) a few inconsistencies in internal auth logic were spotted.
Some places were still using the `DARA_JWT_TOKEN` const instead of checking whether they should use the pageId key.
The logic within `dara.core` has been cleaned up, all places using the token are now going through a centralized `getToken` or `getTokenKey` method which check which key to look up the token at. 
Also fixed too narrow typing on `useVariable`.
Including build for 1.1.2.
Tested the logic still works for basic/implicit auth in non-embedded env and stores under the correct global key, embedded environment stores under provided page id. Full embedded testing TBD pending further debugging of aforementioned issue (see Jira ticket).
Standard …

Improvement: DO-1680 internal auth logic consistency

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/dara/core/definitions.py
packages/dara-core/dara/core/interactivity/actions.py
packages/dara-core/dara/core/interactivity/any_variable.py
packages/dara-core/dara/core/internal/tasks.py
packages/dara-core/dara/core/internal/websocket.py
packages/dara-core/dara/core/js_tooling/js_utils.py
packages/dara-core/dara/core/visual/components/__init__.py
packages/dara-core/dara/core/visual/components/dynamic_component.py
packages/dara-core/package.json
packages/dara-core/pyproject.toml
packages/dara-core/tests/python/test_download.py
packages/dara-core/tests/python/test_main.py
packages/dara-core/tests/python/test_websocket.py
pnpm-lock.yaml
poetry.lock
pyproject.toml

In certain environments we need `get_current_value` default behaviour to be overriden.
The simplest solution applied here was adding a `ContextVar` in the module storing a callable which can be set before running code utilising the API. When provided, the function will instead call the provided custom function.
See Jira for further context
`get_current_value` was made a freeform function in the module to allow calling on a serialized variable without having to instantiate the class programmatically.
The method was left on `AnyVariable` as a convenience API.
Other fixes included:
- fixed ComponentInstance's `__repr__` function using `dict()` instead of the `jsonable_encoder`, the latter should correctly serialize it in more cases
- correctly set `USER`,  `SESSION_ID`, `ID_TOKEN` context …

Improvement: DO-1722 get_current_value behaviour customization

---

docs/advanced/custom-templates.md
docs/faq.md
docs/packages/dara-components/plotting/plotting_palettes.md

This PR covers DO-1734, DO-1743 and DO-1744 and fixes broken imports for palettes and configuration

Docs: DO-1734 fix broken imports in docs

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Build:1.1.4

---

docs/faq.md

Docs: DO-1772 Fix docs links

---

packages/dara-core/dara/core/internal/routing.py
packages/dara-core/dara/core/visual/dynamic_component.py

Currently, there is no way to know the component instance uid in the handlers.
Assigns a contextvar to hold the current component's instance uid.
Locally

Feat: DO-1739: Add cell instance id context var

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/dara/core/internal/websocket.py
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Now specified `anyio>=4.0.0`, as some breaking change are not backwards-compatible and break if used with older anyio version.

Build:1.1.5

---

Makefile
packages/dara-components/dara/components/common/dropzone.py
packages/dara-core/dara/core/internal/registries.py
packages/dara-core/dara/core/internal/registry.py
packages/dara-core/dara/core/internal/registry_lookup.py
packages/dara-core/dara/core/internal/routing.py
packages/dara-core/tests/python/test_upload.py

Bugfix on uploadZone failed
Instead of using `resolver = action_registry.get(resolver_id)`
Use `resolver = await registry_mgr.get(action_registry, resolver_id)`, which can support external resolver
None
Locally tested

Fix: DO-1794 uploadZone resolver bugfix

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Build:1.1.7

---

packages/dara-components/js/graphs/index.tsx

Enterprise version of the graph needed some imports available on top level.
Added necessary imports to top level
None
Locally that causal graph still works and that dara-enterprise also has all it needs available to it.

Fix: DO-1678: exposing import needed for internal version of graph (3/4)

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/dara/core/base_definitions.py
packages/dara-core/dara/core/interactivity/any_variable.py
packages/dara-core/dara/core/interactivity/derived_variable.py
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Minor release as it includes recent cache improvements.
Added minor fixes I found while testing in other projects:
- added convenience `Cache.Policy.from_dict` method
- allowed async functions for `get_current_value` override implementations
- fix store.set called in derived variable logic in few places without checking if cache is set

Build:1.2.0

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Making a 1.3 release with the internals change.
Could have been a patch but separating to leave 1.2.x as LTS for 2023.10.

Build:1.3.0

---

docs/faq.md

This issue was found by an user when building an app and some Plotly figures would not render
I was unable to recreate the issue, this seems to come and go quite inconsistently. For now I have added an entry to the FAQ section of what they can do when encountering it in the future. And if someone does come across this hopefully we can get an example to try and apply a more permanent fix to. 
None

Docs: DO-1842: plotly error value error

---

packages/dara-core/dara/core/internal/encoder_registry.py
packages/dara-core/tests/python/test_encoders.py

DerivedVariable failed to return dataframe which contains nan 
Add a dataframe enocder
None
Locally tested

Fix: DO-1954 Add dataframe encoder

---

packages/dara-core/dara/core/interactivity/derived_variable.py
packages/dara-core/dara/core/internal/encoder_registry.py
packages/dara-core/dara/core/visual/dynamic_component.py
packages/dara-core/tests/python/test_encoders.py

DataFrame should be serialised to dict rather than json string
No
unit tested

Fix: DO-1979 DataFrame serialization to dict

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/dara/core/internal/routing.py
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Releasing action changes to start integrating them into other projects

Build:1.4.0

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/js/index.tsx
packages/dara-core/js/shared/index.tsx
packages/dara-core/js/shared/interactivity/index.tsx
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Bugfix release
Also re-added an export removed in the action refactor, was still used in a project

Build:1.4.1

---

packages/dara-components/changelog.md
packages/dara-components/js/common/input/input.tsx

Claudia found that when starting NumericInput with Variable(), it displayed 0 instead of appearing empty
This was because Number(null) returns 0and not null. Although the variable contained the correct value the display did not match the same behaviour.
How the component behaves:
If starting with Variable() -> empty display
If Variable has a number -> displays the number
If Variable contains a string that can be converted to a number -> displays the number
If Variable contains something that cannot be converted to a number -> empty display
I checked that the above is followed for both initialising the Variable with those and by updating the Variable value through an action
None
Locally for all the scenarios covered above

Fix: DO-2027 none in numeric input shows 0

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Build:1.4.2

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Releasing a patch with the latest perf improvement

Build:1.4.3

---

packages/dara-components/changelog.md
packages/dara-components/dara/components/plotting/plotly/themes.py
packages/dara-components/js/plotting/plotly/plotly.tsx

When testing in Notebook environments it was found that Plotly could have a jittery behaviour or take no height.
Also looked at an issue where the Plotly's tooltip did not use Manrope as the default font.
The issue seems to be one with [Plotly's autosizer](https://stackoverflow.com/questions/76325663/plotly-graph-is-collapsed-in-jupyter-lab-unless-i-specify-the-height). To work around this, I have added the `Autosizer` we already use for other components, such as scrollable `Stack`, `Table` etc around the Plotly's component. This seemed to stop the jittery behaviour however without a `min-height` the plot could render with 0 `height` in situations where the parent sizes itself based off the child component.
To follow in line with the behaviour of other components, I have added a …

Fix: DO-1999 DO-1951 investigate plotly jittery behaviour

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Patch - plotly bugfixes, update action fix

Build:1.4.4

---

docs/best-practices/app-structure-breakdown.md
docs/getting-started/actions.md
docs/getting-started/handling-data.mdx
docs/getting-started/interactivity.mdx
docs/packages/dara-components/graphs/introduction.mdx
docs/packages/dara-components/plotting/bokeh_events.md
docs/packages/dara-components/plotting/plotly_events.md
docs/packages/dara-core/data.mdx
packages/create-dara-app/create_dara_app/templates/default/{{ cookiecutter.__project_slug }}/{{ cookiecutter.__package_name }}/pages/components_page.py
packages/create-dara-app/create_dara_app/templates/default/{{ cookiecutter.__project_slug }}/{{ cookiecutter.__package_name }}/utils/components.py
packages/create-dara-app/create_dara_app/templates/default/{{ cookiecutter.__project_slug }}/{{ cookiecutter.__package_name }}/utils/template.py
packages/dara-components/dara/components/common/accordion.py
packages/dara-components/dara/components/common/button.py
packages/dara-components/dara/components/common/checkbox_group.py
packages/dara-components/dara/components/common/dropzone.py
packages/dara-components/dara/components/common/form.py
packages/dara-components/dara/components/common/table.py
packages/dara-components/dara/components/graphs/components/__init__.py
packages/dara-components/dara/components/graphs/components/causal_graph_viewer.py
packages/dara-components/dara/components/graphs/components/edge_encoder.py
packages/dara-components/dara/components/smart/data_slicer/extension/filter_status_button.py
packages/dara-components/dara/components/smart/data_slicer/utils/core.py

With the new API for actions out a lot of examples in our docs were using the deprecated version
Updated examples throughout the docs to use the new action API

Docs: DO-2133 update docs for new action api

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/internal/import_discovery.py

The import discovery warnings are usually not very helpful an can be very spammy in some cases. Moving the warning to the optional debug logger so it's an opt-in rather than a default warning.

Improvement: DO-2208 move import discovery warning to debug logger

---

docs/advanced/styling-components.md
docs/packages/dara-components/plotting/introduction.mdx
packages/dara-components/dara/components/common/text.py
packages/dara-core/dara/core/configuration.py

Addressing some docs feedback received.
One of the feedback points included docs for the config. We should eventually prepend all the ones we don't intend people changing with underscore. For this however I have just added docs to the ones we expect users to change.
There were some broken links addressed.
It was said that would be nice to have a font size example on Text component.
And added a tip to use sizing_mode when using Bokeh as their plotting tool.

Docs: DO-2193 pilot feedback on dara docs

---

packages/dara-components/dara/components/graphs/components/causal_graph_viewer.py
packages/dara-components/dara/components/graphs/components/edge_encoder.py

Small docs improvements:
- Adds an example on how to use EditorMode in CausalGraphViewer
- Fixes the import for EdgeConstraints in VisualEdgeEncoder

Improvement: DO-2039 Graph components docs improvements

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Build:1.5.1

---

docs/getting-started/actions.md

Fixing incorrect links on the action docs page. They are now relative to other sections on the page

Fix: DO-2257 action links

---

packages/dara-components/dara/components/common/image.py
packages/dara-components/dara/components/graphs/components/base_graph_component.py
packages/dara-components/dara/components/graphs/components/edge_encoder.py
packages/dara-components/dara/components/graphs/definitions.py
packages/dara-components/dara/components/graphs/graph_layout.py

User feedback: When changing some of the params for graph layouts it was hard to know where to start from without being aware of the default values. 
Updated graph docs so that default values are more easily visible.
None

Docs: DO-2279 custsup add default values to docs for graph layouts

---

packages/dara-components/dara/components/graphs/components/base_graph_component.py

Fix incorrect link format causing docs build to crash

Fix: DO-2358 zoom thresholds link

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Build:1.5.3

---

docs/best-practices/laying-out-apps.md

Some people had difficulties with hug and Graph/Table components. Based on feedback it was worth adding a small section in the docs briefly explaining the issue.
Updated the docs on lay it out page to include explanation of why some components became so small within a hug component.

Docs: DO-2316: updating layout docs

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Build:1.6.2

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Build:1.6.3

---

packages/dara-components/js/common/dropzone/dropzone.tsx

Using `RequestExtras` allows us to pass any headers when uploading files, not just `sessionToken`.
Locally

Fix: DO-2567: Use RequestExtras for UploadDropzone

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/internal/normalization.py
packages/dara-core/dara/core/internal/registry_lookup.py
packages/dara-core/dara/core/persistence.py
packages/dara-core/js/shared/interactivity/persistence.tsx
packages/dara-core/tests/python/test_persistence.py

This PR includes fixes and improvements to the `BackendStore` implementation, found when attempting to integrate it into an internal product.
Biggest DX improvement is the introduction of default params, so now the API can be shortened to:
```python
from dara.core import Variable
from dara.core.persistence import BackendStore
var = Variable(store=BackendStore())
```
for a simplest collaborative variable, which defaults to the in-memory backend and a random store uid. 
Both can still be customized if need be.
Other improvements are listed in the changelog.
Simplified BackendStoreSync implementation to use a map to lookup store->extras. This was necessary as the previous approach of serializing extras into the itemKey does not work for reading, as it alters what Recoil-Sync considers to be …

Improvement: DO-2551 BackendStore tweaks

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Releasing latest fix from #213 
Also includes upload fixes (previously backported to 1.6.x)

Build:1.7.2

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Releasing pending bugfixes to unblock other projects

Build:1.7.4

---

packages/dara-components/dara/components/graphs/components/edge_encoder.py
packages/dara-components/js/graphs/visual-edge-encoder.tsx

VisualEdgeEncoder was missing this prop

Fix: DO-2719: require_focus_to_zoom missing prop to edge encoder

---

bearer.yml
docs/advanced/persistence-and-collaboration.mdx
docs/getting-started/interactivity.mdx
docs/sidebar.json
packages/dara-core/dara/core/interactivity/plain_variable.py
packages/dara-core/dara/core/persistence.py

The recently added collaboration/persistence feature wasn't documented outside of the changelog so adding a page to dive deeper into how it works.
Linked from the sidebar and in a tip in the interactivity section.

Docs: DO-2673 add docs page about persistence and collaboration

---

docs/advanced/persistence-and-collaboration.mdx

For some reason the new collaboration page had a wrong whitespace character in headings which made it render incorrectly on our docs site. Fixed by re-adding the whitespace with normal spaces
Before:
After:

Docs: fix whitespace in persistence&collaboration page

---

packages/dara-components/dara/components/common/button.py

There were a couple of typos in the Button docs:
- single quotation mark that not meant to be there
- buton -> button
- defult - > default

Fix: DO-2806 Button docs typos

---

packages/dara-components/package.json
pnpm-lock.yaml

Currently, `remark-gfm` and `react-markdown` is not running on the latest versions. This change bumps up their versions to the latest.
Bumped up `react-markdown` and `remark-gfm`
N/A
Locally

Improvement: DOS-869 Upgraded remark functionality

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Releasing changes made in #252

Build:1.8.0

---

packages/dara-core/changelog.md
packages/dara-core/js/api/websocket.tsx

Fix a missing interface definition for the newly added function
Added the missing def
No
Tested Locally

Fix: DOS-887 Fix Websocket Interface

---

packages/dara-components/js/common/dropzone/dropzone.tsx
packages/dara-core/changelog.md
packages/dara-core/js/api/core.tsx
packages/dara-core/js/shared/interactivity/data-variable.tsx
packages/dara-core/js/shared/interactivity/derived-variable.tsx
packages/dara-core/js/shared/interactivity/use-server-component.tsx
packages/dara-core/js/shared/utils/use-action.tsx

It's been reported that there are issues in an internal product where features (using e.g. Dara actions) stop working due to login expiring but the user is not kicked out to the login page immediately.
After investigating, I found that the issue was due to the action request not handling auth errors properly. With the fix upon an auth error the user will be immediately redirected to the login page. 
Looking through internal requests made, that piece of logic was missing for few other requests so I've also fixed those for consistency.
Added `handleAuthErrors` call to each usage of `request` within Dara internals (derived variables, py_components, actions etc). This catches auth errors thrown by Dara and redirects to login page if one is found.
Verified actions were the issue in the …

Fix: DO-2868 redirect to login on auth errors in internal requests

---

packages/dara-components/changelog.md
packages/dara-components/js/smart/chat/chat.tsx

Found error in the logic when testing in the internal product
Updated the logic so it correctly handles when a chat initially has no messages as you add and delete them.
Locally

Fix: DO-2889 empty chat bug

---

docs/packages/dara-components/graphs/introduction.mdx
packages/dara-components/changelog.md
packages/dara-components/dara/components/graphs/components/base_graph_component.py
packages/dara-components/dara/components/graphs/components/edge_encoder.py

User found that `default_legends` did not work with `None` even though its type indicated optional.
Updated so that `default_legends` type does not indicate that None is accepted. It will now throw the appropriate error if None is passed to it, rather than failing in the front end.
Also added an example in the docs as to how one can update default_legends
None
Locally on a demo app

Fix: DO-2883: remove optional for default legends as it doesnt accept none

---

borg.toml
lerna.json
packages/create-dara-app/pyproject.toml
packages/dara-components/changelog.md
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Patch so that we can add the chat fix before testing happens, without these changes people can not add messages to a new chat oops.

Build:1.8.2

---

packages/dara-components/changelog.md
packages/dara-components/js/common/markdown/markdown.tsx
packages/dara-components/package.json
pnpm-lock.yaml

To use dara-ui Markdown component, as to avoid duplicates across the product
Updated to use dara-ui Markdown component
None
Locally

Improvement: DO-2837 dara to use dara UI markdown component

---

packages/dara-components/changelog.md
packages/dara-components/js/smart/chat/chat.tsx

In internal product user wanted to add multiple chats to the same page
Changed so that the chat button that opens the thread now is set with relative to the parent. This allows the user to see multiple chats on the same page.
Since the threads are slightly transparent as per design, this meant that if multiple were open they would overlap, so one addition was for based on the number of threads on the page to set the latest opened to have a z-index higher than the others present.
If there were multiple threads we also add a background color so that chats below current are not visible.

Improvement: DO-2850 attach chat button as overlay within the component instance

---

packages/dara-core/changelog.md
packages/dara-core/js/shared/interactivity/data-variable.tsx
packages/dara-core/js/shared/interactivity/use-data-variable.tsx
packages/dara-core/js/shared/interactivity/use-variable.tsx
packages/dara-core/js/types/event-types.tsx
packages/dara-core/tests/js/use-data-variable.spec.tsx
packages/dara-core/tests/js/use-variable.spec.tsx

Further investigation around original use case for the EventBus uncovered the need for more events. Now all variable types (which are not synchronous, i.e. all except UrlVariable since even PlainVariable can have a derived variable as a default) should fire update events. 
Added `DATA_VARIABLE_LOADED` and `DERIVED_DATA_VARIABLE_LOADED` events to the event bus, fired by the `useFetch...` hooks when a request is fully resolved.
Updated tests

Improvement: DO-2845 add data variable EventBus events

---

docs/getting-started/actions.md
docs/getting-started/handling-data.mdx

Issue was raised with found typos in the docs
closes #288
Addressed the docs issues found and also updated to use `Label` in one of the examples instead of a horizontal stack, to show a different way of doing it. Also in the given example it made the page look nicer due to default behaviour of Stack vs Label.
None
By running the examples locally

Docs: DO-2979: fixing docs

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/auth/routes.py
packages/dara-core/js/auth/auth.tsx
packages/dara-core/js/auth/basic/basic-auth-login.tsx
packages/dara-core/js/auth/default/default-auth-login.tsx
packages/dara-core/js/shared/private-route/private-route.tsx
packages/dara-core/tests/python/test_auth.py

This PR fixes an issue where the 'referrer' feature which was meant to redirect the user back to the original page after an auth error and a login was not working consistently.
This will be followed by updates to the internal SSO login system.
There were a couple of issues spotted:
- The backend auth endpoint had `HTTPBearer` FastAPI dependency with default arguments, which included `auto_error=True`; this causes it to raise its own error in case of missing token rather than let us handle it. Our client-side logic expects specific defined auth error messages which meant the referrer logic did not run for missing tokens. Now malformed auth headers (wrong scheme, missing token) explicitly return a 400 error
- The two main redirection parts in Dara, `handleAuthErrors` which runs on all API …

Fix: DO-2977 preserve app url after login

---

borg.toml
lerna.json
package.json
packages/create-dara-app/pyproject.toml
packages/dara-components/package.json
packages/dara-components/pyproject.toml
packages/dara-core/changelog.md
packages/dara-core/package.json
packages/dara-core/pyproject.toml
pnpm-lock.yaml
poetry.lock
pyproject.toml

Patch release with #293 to pick up in internal packages
Fixed a small peer-dependencies resolution issue with react-markdown, overriding its deps in top-level `package.json` for now

Build:1.9.1

---

packages/dara-components/changelog.md
packages/dara-components/dara/components/graphs/components/causal_graph_viewer.py

A couple of users were confused about the different `editor_mode`s that we have available.

Docs: DO-2960: Clarify docs for editor_mode in CausalGraphViewer

---

docs/advanced/styling-components.md
docs/faq.md
docs/getting-started/interactivity.mdx
packages/dara-components/dara/components/graphs/graph_layout.py
packages/dara-core/dara/core/configuration.py
packages/dara-core/dara/core/metrics/utils.py

Fixing some formatting in docs in order to comply with internal docs requirements
Added line breaks, escapes and wrapping in code quotes
None

Docs: DO-3022: formatting docs fixes

---

docs/advanced/custom-templates.md

User found wrong import and reference where bar frame had lower case b

Docs: DO-3136: fix bar frame docs

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/interactivity/plain_variable.py
packages/dara-core/tests/python/test_variable.py

This PR implements a static contextmanager method on the `Variable` class, `init_override`. It takes a callable which is invoked with the provided variable kwargs and can choose to transform them. This is intended for advanced use cases where the random variable uids can be e.g. restored when rerunning the same piece of code, or the uids can be stored externally and mapped from the old uid set to the new one.
Implemented as a ContextVar. Static method added for convenience.
Unit test added.

Feat: DO-3010 implement Variable.init_override contextmanager

---

packages/dara-core/changelog.md
packages/dara-core/js/shared/interactivity/plain-variable.tsx
packages/dara-core/js/shared/interactivity/use-variable.tsx
packages/dara-core/js/types/event-types.tsx
packages/dara-core/tests/js/use-variable.spec.tsx

The `EventBus` was not emitting updates for `UrlVariables`, for completeness it now does.
Added a unit test

Improvement: DO-3142 add EventBus events for UrlVariable

---

packages/dara-components/js/common/select/select.tsx
packages/dara-core/changelog.md
packages/dara-core/js/shared/interactivity/use-variable.tsx

In certain conditions when the Select `value` is a nested dictionary selecting a new value from the dropdown causes an infinite loop. The reason seems to be related to an edge case in an interaction between Recoil and Downshift causing the `onSelect` to retain a stale value after forcing a rerender, which then tries to set the value back to its current state.
```py
from dara.components import Select
from dara.core import Variable, py_component, DerivedVariable
dict_var = Variable({x: None for _ in range(10)})
other_var = Variable(0)
derived_var = DerivedVariable(
lambda x, y: True, variables=[dict_var, other_var],
deps=[other_var]
)
@py_component
def MyComponent(_):
return Select(items=['a', 'b', 'c'], value=dict_var.get(6))
MyComponent(derived_var)
```
It's not always reproducible, on …

Fix: DO-3161: Fix infinite loop when a nested selector is used in Select

---

Makefile

The PyPi proxy has been disabled so the docs action needs to be updated.
Assigning `causalens` artifactory source to be supplemental seems to do the trick.

Fix: DO-3236: Fix docs build action

---

.github/workflows/release.yml
Makefile
packages/dara-core/changelog.md

The CI workflow was resetting JS changes in the version bump commit. It now commits them before publishing and pushes only after the publishing successfully, as lerna doesn't support publishing with unsaved changes.

Fix: DO-3236: Fix JS commit push CI

---

packages/ui-components/src/chat/chat.stories.tsx
packages/ui-components/src/chat/chat.tsx
packages/ui-components/src/chat/message.tsx
packages/ui-components/src/types.tsx

Added functionality to append actions to a message. Actions will be additional elements that will be rendered with the message if the user plans to add additional functionality to the message.
- Added actions property to `Message`
- Passed this to `Message` component to be rendered in the UI
Locally

Improvement: DO-3471 Added message actions to show for each message

---

packages/dara-components/changelog.md
packages/ui-causal-graph-editor/package.json
packages/ui-code-editor/package.json
packages/ui-components/package.json
packages/ui-components/src/chat/chat.stories.tsx
packages/ui-components/src/chat/chat.tsx
packages/ui-components/src/chat/message.tsx
packages/ui-components/src/markdown/markdown.tsx

After testing latest changes in internal product, we realized the dark code viewer theme in light mode is too overbearing. In the future we can revisit that approach, perhaps find a 'less black' dark theme.
In the meantime:
- added a light border to the code viewer in markdown 
- fixed missing spacing between chat message header and chat message body
- added missing cursor:pointer for message icons
Fixed an ESLint rule about missing effect dependency by using 'latest ref' pattern for localMessages.
I noticed we were missing the `lint` script in some packages hence it got missed, added them back.
Locally
https://github.com/user-attachments/assets/7e5c07d7-f976-4599-8b68-b81545cbfb1f

Improvement: DO-3456 chat code viewer visual tweaks

---

packages/ui-components/changelog.md
packages/ui-components/src/markdown/markdown.tsx

Issues spotted with the default markdown styling. We were trying to follow [Tailwind Typography](https://github.com/tailwindlabs/tailwindcss-typography/tree/master) styling but missed the mark in few places. This PR brings our styling closer to the good defaults. Most notable changes:
- table styling now properly displays light borders between rows
- table now left-aligns headers
- table is now full width
- blockquotes now display quotes, they were not showing due to few missing CSS properties
- improved figcaption to stand out from normal text
- colored bullet points grey as in Tailwind's plugin
By locally running the [Typography demo](https://play.tailwindcss.com/uj1vGACRJA?layout=preview) side by side with the equivalent in Dara

Improvement: DO-3542 default `Markdown` styling tweaks

---

packages/ui-components/changelog.md
packages/ui-components/src/input/input.tsx
packages/ui-components/src/numeric-input/numeric-input.tsx

Previously, `Input` and `NumericInput` did not accept standard HTML props as it doesn't extend from the `InputHTMLAttributes<HTMLInputElement>` interface. Now they both do, so we can remove the redundant props being passed and use all standard html props without issues.
Locally

Improvement: DO-3640: Input and NumericInput now accept standard HTML element props

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/interactivity/filtering.py
packages/dara-core/js/shared/interactivity/data-variable.tsx
packages/dara-core/tests/js/use-data-variable.spec.tsx
packages/dara-core/tests/js/utils/test-server-handlers.tsx

Fixed a crash in `Table` when rendering the result of a `DerivedDataVariable` due to a missing `cache_key`.

Fix: DO-3637: Fix rendering of tables from DerivedDataVariables

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/interactivity/derived_data_variable.py
packages/dara-core/dara/core/internal/routing.py
packages/dara-core/tests/python/test_derived_data_variable.py

The table schema for DDVs is using the `derived_variable_registry` as it doesn't need any filtering. The route for `/schema` was incorrectly using `data_variable_registry` for both cases.

Fix: DO-3682: Use the other registry type for DDVs `/schema` endpoint

---

packages/dara-components/dara/components/smart/__init__.py
packages/dara-components/dara/components/smart/data_slicer/__init__.py
packages/dara-core/changelog.md
packages/dara-core/dara/core/interactivity/data_variable.py
packages/dara-core/dara/core/interactivity/derived_data_variable.py
packages/dara-core/dara/core/internal/routing.py
packages/ui-components/changelog.md

User was passing `dataframe.describe()` as the data to a `Table` component, in this case one of their columns was of type `datime64`. Instead of showing the datetime values formatted as one would expect when printing this information, the table instead showed the dates as timestamps.
Looking closer at the issue, the `describe` method in pandas for `datetime64` columns returns a column of type `object`. This is because `object` is the more generic type, the resulting column is a mixture of datetime and number values. Due to this the Table component was not able to infer the correct types and when the data was serialized Timestamp(...) became just the timestamp string.
What we can do to address the issue is the same that pandas does in their `__repr__` for this type of column, which is to …

Fix: DO-3745 table display does not format datetime columns correctly

---

packages/dara-components/changelog.md
packages/dara-components/dara/components/plotting/plotly/plotly.py

User found that in their bar chart that uses plotly express that the bar colors appeared purple, whereas in normal plotly bar it appeared with our primary blue color.
It seems that when using plotly express, the bar colors are passed to the marker property in the `data` of the figure. 
Since we don't know what `data` a figure will have, on the `Plotly` component we set our colors as part of the `layout` property of the figure. 
Based on perusing through plotly's code, when plotly express's bar method is called it looks for the `color` property set in the currently active template. Which means that it gets the default first color available in plotly's default theme (the purple we see).
To address this I have added at the top level so that when `Plotly` component is imported we also set the …

Fix: DO-3936 bar plot not picking up default dara styling with plotly

---

packages/dara-core/changelog.md
packages/dara-core/js/types/utils.tsx

User was trying to render a Plotly figure on internal product that had over a million data points. This caused Plotly component to break with "too many properties to enumerate error"
Looking through the error the issue was found to be triggered by this line:
`Object.keys(variable).includes('uid')`
variable in this case included the plotly figure which due to its size had a substantial amount of properties.
The suggested fix is to use `hasOwnProperty` instead. This avoids the overhead of creating an array of keys and improves performance by checking only the necessary property.
None
By applying the change on internal product where the issue occurs

Fix: DO-3941 custsup plotly with too many data points breaks with enumerate error

---

packages/dara-components/dara/components/smart/chat/chat.py

Could not release dara website because chat image path was one level off
Ran dara website locally with latest of dara and checked that this allowed the app to build

Fix: DO-3993: path for chat image fix

---

.github/workflows/publish_docs.yml

publish-docs workflow was failing

Fix: DO-3994: update publish docs to use correct version of poetry

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/auth/routes.py
packages/dara-core/js/api/http.tsx
packages/dara-core/js/jest-setup.ts
packages/dara-core/package.json
packages/dara-core/tests/js/http.spec.tsx
pnpm-lock.yaml

Issue noticed when testing refresh logic in internal product, seems to be working except there's unnecessary body data sent in the request from the original failing request.
By mistake I previously included the original request `RequestInit` data in the refresh request.
Once fixed I had to tweak the test setup to ensure `credentials: include` is set on the `fetch` calls in jest. In the browser the requests we make are same-origin so it's not necessary, but in the test runner they are treated as cross-origin so the extra setting is necessary. 
`@types/whatwg-fetch` because of the test setup above

Fix: DO-3034 remove redundant data from refresh request

---

.github/CODEOWNERS

Change repo ownership to capture the whole apps team

Improvement: DO-3687 change repo ownership to capture the whole team

---

docs/faq.md

Docs: DO-4286 DO-4309 dark theme link

---

packages/dara-components/changelog.md
packages/dara-components/dara/components/common/button.py
packages/dara-components/dara/components/common/button_bar.py
packages/dara-components/dara/components/common/datepicker.py
packages/dara-components/dara/components/common/if_cmp.py
packages/dara-components/dara/components/common/input.py
packages/dara-components/dara/components/common/label.py
packages/dara-components/dara/components/common/radio_group.py
packages/dara-components/dara/components/common/select.py
packages/dara-components/dara/components/common/slider.py
packages/dara-components/dara/components/common/switch.py
packages/dara-components/dara/components/common/tabbed_card.py
packages/dara-components/dara/components/common/textarea.py

often times in the reference docs we don’t assign our variables to a value we use them directly in the component ie:
```python
Input(value=Variable('test'))
```
99% of the time we would want to assign our variable like the following:
```python
value_var = Variable('test')
Input(value=value_var)
```
so we can actually get access to that value later on in our component/apps
updated the reference docs to avoid this bad practice so that the dara agent does not pick this habit up
updated some reference docs

Improvement: DO-4388 updated reference docs with defined variables

---

.github/workflows/publish_docs.yml
.github/workflows/release.yml

Updating deprecated action version

Fix: DO-5165 update actions/cache v3->v4

---

packages/ui-components/changelog.md
packages/ui-components/src/multiselect/multiselect.tsx
packages/ui-components/src/numeric-input/numeric-input.tsx

Currently, we show two error messages since the error message for numeric input is a duplicate of the one for `Input`
Also, multiselect does not show the errored state properly.
- Removed the error message for numeric input.
- Added the property for errored to the multiselect.
N/A
Locally

Fix: DO-5436 - Form item changes

---

packages/dara-core/dara/core/main.py

Issue spotted when using Dara in combination with other libraries. When they mess with adding a root logger, the `eng_logger` which we intend to disable still propagates its messages so it doesn't get disabled correctly.
Tested locally in a Dara app where previously eng logger would stay enabled by default

Fix: DO-5493 eng logger disable not working

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/visual/components/__init__.py
packages/dara-core/tests/python/test_components.py

Issue reported
```
File "...", in __init__
validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "...", line 100, in __getattr__
raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `Default` is not fully defined; you should define `Optional`, then call `Default.model_rebuild()`.
```
Due to the usage of future annotations we need to rebuild models a bunch, and Fallback slipped through the cracks as there wasn't test coverage for it.
Added a regression test that uses a component, will spot whether the component can be build correctly.

Fix: DO-5864 `Fallback` not serializing correctly

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/cli.py
packages/dara-core/dara/core/main.py

Updates the following envs to match `fastapi_vite_dara` implementation:
`VITE_REACTJS_HMR` -> `VITE_IS_REACT`
`VITE_SERVE_MODE` -> `VITE_HOT_RELOAD`

Fix: DO-5985: Update fastapi_vite_dara envs

---

packages/dara-core/dara/core/visual/components/__init__.py

Removes warnings when running Dara apps:
```
{'title': 'Error rebuilding model "js_module=\'@darajs/core\' js_component=None py_module=\'dara.core\' name=\'DynamicComponent\' type=<ComponentType.JS: \'js\'>": issubclass() arg 1 must be a class'}
{'title': 'Error rebuilding model "js_module=\'@darajs/core\' js_component=None py_module=\'dara.core\' name=\'DefaultFallback\' type=<ComponentType.JS: \'js\'>": issubclass() arg 1 must be a class'}
{'title': 'Error rebuilding model "js_module=\'@darajs/core\' js_component=None py_module=\'dara.core\' name=\'RowFallback\' type=<ComponentType.JS: \'js\'>": issubclass() arg 1 must be a class'}
{'title': 'Error rebuilding model "js_module=\'@darajs/core\' js_component=None py_module=\'dara.core\' name=\'Menu\' type=<ComponentType.JS: \'js\'>": …
```

Fix: DO-5864 silence warning when starting Dara

---

packages/dara-components/changelog.md
packages/dara-components/dara/components/common/dropzone.py

Another issue spotted in Pydantic v2 migration.
Locally.

Fix: DO-6016 Fix UploadDropzone resolver type hint

---

packages/dara-core/dara/core/internal/encoder_registry.py

Fix: DO-6110 Docstrings fix

---

docs/advanced/persistence-and-collaboration.mdx
packages/dara-core/changelog.md
packages/dara-core/dara/core/persistence.py
packages/dara-core/js/shared/interactivity/persistence.tsx
packages/dara-core/js/types/core.tsx
packages/dara-core/tests/js/persistence.spec.tsx
packages/dara-core/tests/python/test_persistence.py
packages/dara-core/tests/python/utils.py

This PR extends the base `PersistenceBackend` for variable `BackendStore` to be able to support subscriptions. This way the storage layer can notify the UI about new values.
- subscribe takes a simple callback passed from BackendStore that should be invoked with new keys/values
- new `readonly` flag is serialised down to the UI and disables the `write` part of the SyncEffect to not fire redundant calls to the backend
Tests, tested locally with a custom backend store persistence layer

Feat: DO-6314 support backend store subscriptions

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/persistence.py
packages/dara-core/tests/python/test_persistence.py

Issue found when testing recent additions to BackendStore. When creating one within a py_component it would capture the WS_CHANNEL from scope and thus subscribed updates would not be sent to the user creating the store. Fixed by adding extra flags to internal notify functions and making sure the subscription notifications go out to everyone.
Also changed backend store registration to be a soft info log rather than an error. In some cases it's valid to attach the same store to multiple variables (i.e. to cache a given store), left an info log to make sure for invalid use cases users are still aware in case it's a mistake.
Locally in an app

Fix: DO-6314 BackendStore created within a py_component would not notify its creator about subscribed updates

---

packages/dara-components/js/common/table/table.tsx

When an error occurs during data fetching, e.g. due to invalid json data produced, the errors are currently silently ignored. For now added a console error to make them easier to debug in the future.

Improvement: DO-6357 add log for errors in table data fetching

---

packages/ui-causal-graph-editor/package.json
packages/ui-causal-graph-editor/src/graph-viewer/causal-graph-editor.tsx
packages/ui-causal-graph-editor/src/shared/use-graph-tooltip.tsx
packages/ui-components/changelog.md
packages/ui-components/package.json
packages/ui-components/src/multiselect/multiselect.stories.tsx
packages/ui-components/src/tooltip/tooltip.tsx
pnpm-lock.yaml

Fixes an issue where clicking too fast in a controlled MultiSelect would cause an infinite loop. The cause was identified to be tippy.js. Since tippy.js is now deprecated and archived, we have migrated Tooltip to floating-ui, which we already use for other components. This was the last remaining tippy.js component, so we can now safely remove it from our deps.
The external API did not change and was reimplemented using floating-ui's hooks.
The only other usage was `GetReferenceClientRect` tippy.js type, which was replaced with a `DOMRect` implementation since it automatically calculates the other properties.
Removed tippy.js
Storybook and demo app. Added more stories.

Improvement: DO-6248: Fix Tooltip infinite loop, Remove tippy.js, Migrate Tooltip to floating-ui

---

packages/dara-components/changelog.md
packages/dara-components/js/common/input/input.tsx
packages/dara-components/js/common/slider/slider.tsx

With the recent Slider changes in #430 I realized I added an internal/actual variable value split to support controlled mode with a debounce but I forgot to add a sync back to handle external variable changes. This PR fixes it, see:
https://github.com/user-attachments/assets/c71509c4-29b7-4c07-ba57-c6735dd9eea1
Without the change, updating the input would not update the slider. Code used:
```python
slider_var = Variable(default=1)
def page():
return Stack(
Slider(value=slider_var, domain=[0, 10]),
Input(value=slider_var)
)
config.add_page(name='slider', content=page())
```
Locally in a demo app

Fix: DO-6356 regression - slider not updating in response to outside Variable changes

---

packages/dara-components/js/common/if/if.tsx
packages/dara-components/js/common/select/select.tsx
packages/dara-components/js/common/table/table.tsx
packages/dara-core/js/shared/dynamic-component/dynamic-component.tsx
packages/dara-core/js/shared/interactivity/derived-variable.tsx
packages/dara-core/js/shared/interactivity/use-variable.tsx
packages/dara-core/js/types/utils.tsx
packages/dara-core/tests/js/dynamic-component.spec.tsx
packages/dara-core/tests/js/use-data-variable.spec.tsx
packages/dara-core/tests/js/use-variable.spec.tsx
packages/dara-core/tests/js/utils/test-server-handlers.tsx
packages/dara-core/tests/js/utils/wrapped-render.tsx
packages/ui-causal-graph-editor/src/shared/rendering/edge/edge-object.tsx
packages/ui-causal-graph-editor/src/shared/rendering/node/node-object.tsx
packages/ui-components/src/chat/chat.tsx
packages/ui-components/src/chat/message.tsx
packages/ui-components/src/datepicker/datepicker.tsx
packages/ui-components/src/multiselect/multiselect.stories.tsx
packages/ui-components/src/progress-bar/progress-bar.tsx
packages/ui-components/src/shared/dropdown-list.tsx
packages/ui-notifications/src/use-notifications.tsx
packages/ui-utils/src/use-tinykeys.tsx

While testing initial `For` implementation I noticed a few issues that caused elements initially rendered to not 'react' to changes in their data.
1. Dynamic component was missing an effect to re-resolve components when they change. Added a test to cover that.
2. useVariable in the primitive case was simply passing it to `useState` which made it snapshot the first value. Added an extra equality check there to call `setState` when the value changes. Added a test to cover.
3. If component was missing hook dependencies in a memo
I included a small fix to update lodash imports since I noticed we were inconsistent, we use the proper module-specific imports now.
Unit tests added
Tested manually in a dara app, confirmed those fix the issue

Fix: DO-6667 components not updating correctly when data changes inside For component

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/interactivity/data_variable.py

Currently, logging takes into consideration if `entry` is `None` but not if `entry.data` is None. This fix adds an additional check for that to not cause an error.
- Added additional check if `entry.data` is not None.
N/A
Locally

Fix: DO-6852 fix logging issue

---

packages/dara-core/dara/core/interactivity/switch_variable.py

The following error occured when trying to build docs: Could not parse expression with acorn

Fix: DO-6296 Fix docstrings for docs release

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/internal/pool/task_pool.py
packages/dara-core/dara/core/internal/pool/utils.py

Issue reported where an error in the task pool loop would make the global TaskGroup unusable and fail to process further tasks
Traced through the few places we pass the global task group down. 
The only two places not guarded with a try/except were:
-  the worker shutdown coro
-  the main pool loop
These now log and ignore the errors.

Fix: DO-7073 error in task pool loop could cause it to crash

---

packages/ui-components/changelog.md
packages/ui-components/package.json
packages/ui-icons/changelog.md
packages/ui-icons/package.json
pnpm-lock.yaml

Another package released a broken update today. This time locking @fortawesome/react-fontawesome.

Fix: DO-7132: Pin @fortawesome/react-fontawesome

---

packages/dara-core/changelog.md
packages/dara-core/dara/core/defaults.py
packages/dara-core/dara/core/router/components.py
packages/dara-core/js/components/index.tsx
packages/dara-core/js/components/link.tsx
packages/dara-core/js/components/navigate.tsx

Quick improvement needed for one of the projects internally.

Improvement: DO-7486 allow Link components to accept ClientVariable as the to prop, expose Navigate component

---

packages/ui-components/changelog.md
packages/ui-components/src/index.tsx
packages/ui-components/src/markdown/markdown.tsx

Tweaked some markdown heading sizing.
Exported the internal markdown components (styles wrapper and the code display) to make building a more custom markdown renderer easier.

Improvement: DO-7486 export markdown internals

---

packages/dara-core/changelog.md
packages/dara-core/js/router/create-router.tsx
packages/dara-core/package.json
pnpm-lock.yaml

Issue spotted in an app, we didn't lock the react-router version and they dropped the `unstable_` prefix from their middleware API in a recent minor which broke our auth checks and caused an infinite spinner in some cases.
Upgraded to the latest version without the `unstable_` prefix and locked to a minor for now.
Verified the auth issue is gone after dropping the `unstable_` middleware prefix.

Fix: DO-7591 upgrade and lock react-router
